name: oven
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+60

environment:
  sdk: ^3.8.1
# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.1
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  flutter_localizations:
    sdk: flutter
  intl: any
  carousel_slider: ^5.1.1
  in_app_update: ^4.0.0
  upgrader: ^11.5.0
  package_info_plus: ^8.3.1
  shorebird_code_push: ^2.0.4
  url_launcher: ^6.3.1
  buttons_tabbar:

  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: EnglishFont
      fonts:
        - asset: lib/assets/fonts/Lobster-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Poppins-Bold.ttf
          weight: 700
  
    - family: ArabicFont
      fonts:
        - asset: lib/assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: lib/assets/fonts/Cairo-Bold.ttf
          weight: 700



  assets:
    - lib/assets/logo_larg.png
    - lib/assets/logo_small.png
    - lib/assets/facebook_logo.png
    - lib/assets/google_logo.png
    - lib/assets/apple_logo.png
    - lib/assets/Cakes2-1.webp
    - lib/assets/Cakes3-1.webp
    - lib/assets/Cakes3-2.webp
    - lib/assets/Cakes_dark.webp
    - lib/assets/slide1.jpg
    - lib/assets/slide2.jpg
    - lib/assets/slide3.jpg
    - lib/assets/donut.png
    - lib/assets/updateImage.webp
    - shorebird.yaml
  generate: true
flutter_native_splash:
  color: "#ffffff"
  image: "lib/assets/logo_larg.png"
  color_dark: "#000000"            
  image_dark: "lib/assets/logo_dark_small.png"
  android: true
  ios: true
  web: true
  fullscreen: true

  android_12:
    color: "#ffffff"
    image: "lib/assets/logo_small.png"

    color_dark: "#000000"            
    image_dark: "lib/assets/logo_dark_small.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/logo_small.png"
  min_sdk_Android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "lib/assets/logo_small.png"
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  