import 'dart:typed_data';

class ProductSubCategory {
  final String id;
  final String title;
  ProductSubCategory({required this.id, required this.title});
}

class Product {
  final String id;
  final String title;
  final String description;
  final double price;
  final double? discount;
  final List<Uint8List>? images;
  final Uint8List? thumbnail;
  final ProductSubCategory subCategoryId;
  final String? video;
  final Uint8List? cover;
  final bool enabled;
  final int itemsToBox;
  final double? taxAverage;
  final String? connectedProduct;
  final bool enabledImageAttachment;

  Product({
    required this.id,
    required this.title,
    required this.description,
    required this.images,
    required this.thumbnail,
    required this.price,
    required this.discount,
    required this.subCategoryId,
    required this.cover,
    required this.enabled,
    required this.itemsToBox,
    required this.taxAverage,
    required this.enabledImageAttachment,
    this.video,
    this.connectedProduct,
  });
}

final List<Product> englishProducts = [
  Product(
    id: "P1",
    title: "Classic Vanilla Birthday Cake",
    description: "Soft vanilla sponge layered with buttercream frosting.",
    images: null,
    price: 850,
    subCategoryId: ProductSubCategory(id: "12-1", title: "Birthday Cakes"),
    itemsToBox: 5,
    discount: 10,
    thumbnail: null,
    cover: null,
    enabled: true,
    taxAverage: 14,
    connectedProduct: "P2",
    enabledImageAttachment: false,
  ),
  Product(
    id: "P2",
    title: "Chocolate Fudge Birthday Cake",
    description: "Rich chocolate cake with fudge filling.",
    itemsToBox: 5,
    price: 920,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "12-1", title: "Birthday Cakes"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    connectedProduct: "P1",
    enabledImageAttachment: true,
  ),
  Product(
    id: "P3",
    title: "Elegant White Wedding Cake",
    description: "Three-tier wedding cake with floral decoration.",
    itemsToBox: 5,
    price: 4500,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "12-2", title: "Wedding Cakes"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    connectedProduct: "P12",
    enabledImageAttachment: false,
  ),
  Product(
    id: "P4",
    title: "Custom Photo Cake",
    description: "Personalized cake with edible printed photo.",
    itemsToBox: 5,
    price: 1100,
    discount: 5,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "12-3", title: "Custom Cakes"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),

  // ===== CUPCAKES (45-x) =====
  Product(
    id: "P5",
    title: "Vanilla Classic Cupcake",
    description: "Moist vanilla cupcake with cream swirl.",
    itemsToBox: 5,
    price: 35,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "45-1", title: "Classic Cupcakes"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P6",
    title: "Red Velvet Cupcake",
    description: "Soft red velvet topped with cream cheese frosting.",
    itemsToBox: 5,
    price: 40,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "45-1", title: "Classic Cupcakes"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
  Product(
    id: "P7",
    title: "Caramel Filled Cupcake",
    description: "Cupcake filled with salted caramel center.",
    itemsToBox: 5,
    price: 45,
    discount: 5,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "45-2", title: "Filled Cupcakes"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P8",
    title: "Mini Chocolate Cupcakes Box",
    description: "Box of 12 mini chocolate cupcakes.",
    itemsToBox: 5,
    price: 280,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "45-3", title: "Mini Cupcakes"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    connectedProduct: "P6",
    enabledImageAttachment: true,
  ),

  // ===== COOKIES (65-x) =====
  Product(
    id: "P9",
    title: "Classic Chocolate Chip Cookies",
    description: "Crispy outside, chewy inside.",
    itemsToBox: 5,
    price: 120,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(
      id: "65-1",
      title: "Chocolate Chip Cookies",
    ),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P10",
    title: "Double Chocolate Cookies",
    description: "Chocolate dough with dark chocolate chunks.",
    itemsToBox: 5,
    price: 140,
    discount: 8,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(
      id: "65-1",
      title: "Chocolate Chip Cookies",
    ),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
  Product(
    id: "P11",
    title: "Butter Cookies Tin",
    description: "Traditional buttery cookies assortment.",
    itemsToBox: 5,
    price: 220,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "65-2", title: "Butter Cookies"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P12",
    title: "Nutella Stuffed Cookie",
    description: "Large cookie stuffed with Nutella.",
    itemsToBox: 5,
    price: 55,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "65-3", title: "Stuffed Cookies"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),

  // ===== PASTRIES (78-x) =====
  Product(
    id: "P13",
    title: "Apple Danish",
    description: "Flaky pastry filled with apple compote.",
    itemsToBox: 5,
    price: 60,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "78-1", title: "Danish Pastries"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P14",
    title: "Cheese Danish",
    description: "Creamy cheese filled pastry.",
    itemsToBox: 5,
    price: 65,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "78-1", title: "Danish Pastries"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
  Product(
    id: "P15",
    title: "Chicken Puff Pastry",
    description: "Savory puff pastry filled with chicken.",
    itemsToBox: 5,
    price: 75,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "78-2", title: "Puff Pastries"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P16",
    title: "Spinach Puff",
    description: "Crispy puff pastry with spinach filling.",
    itemsToBox: 5,
    price: 70,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "78-3", title: "Savory Pastries"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),

  // ===== TARTS & PIES (31-x) =====
  Product(
    id: "P17",
    title: "Strawberry Tart",
    description: "Fresh strawberries on custard tart.",
    itemsToBox: 5,
    price: 180,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "31-1", title: "Fruit Tarts"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
  Product(
    id: "P18",
    title: "Lemon Tart",
    description: "Tangy lemon curd in buttery crust.",
    itemsToBox: 5,
    price: 170,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "31-1", title: "Fruit Tarts"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
  Product(
    id: "P19",
    title: "Chocolate Cream Pie",
    description: "Rich chocolate cream pie.",
    itemsToBox: 5,
    price: 200,
    discount: 7,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "31-3", title: "Chocolate Pies"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P20",
    title: "Banana Cream Pie",
    description: "Classic banana cream pie.",
    itemsToBox: 5,
    price: 190,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "31-2", title: "Cream Pies"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),

  // ===== CHOCOLATES (46-x) =====
  Product(
    id: "P21",
    title: "Dark Chocolate Bar 70%",
    description: "Premium dark chocolate bar.",
    itemsToBox: 5,
    price: 95,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "46-1", title: "Chocolate Bars"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P22",
    title: "Milk Chocolate Bar",
    description: "Smooth creamy milk chocolate.",
    itemsToBox: 5,
    price: 85,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "46-1", title: "Chocolate Bars"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P23",
    title: "Chocolate Truffles Box",
    description: "Assorted chocolate truffles.",
    itemsToBox: 5,
    price: 350,
    discount: 1,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "46-2", title: "Truffles"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P24",
    title: "Luxury Chocolate Gift Box",
    description: "Premium assorted chocolates.",
    itemsToBox: 5,
    price: 600,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(
      id: "46-3",
      title: "Gift Chocolate Boxes",
    ),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),

  // ===== DESSERT BOXES (28-x) =====
  Product(
    id: "P25",
    title: "Mini Dessert Party Box",
    description: "Assorted mini desserts.",
    itemsToBox: 5,
    price: 480,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "28-1", title: "Mixed Dessert Boxes"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
  Product(
    id: "P26",
    title: "Family Dessert Box",
    description: "Perfect for gatherings.",
    itemsToBox: 5,
    price: 750,
    discount: 5,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "28-1", title: "Mixed Dessert Boxes"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
  Product(
    id: "P27",
    title: "Kids Treat Box",
    description: "Colorful desserts for kids.",
    itemsToBox: 5,
    price: 390,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "28-2", title: "Mini Treat Boxes"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
  Product(
    id: "P28",
    title: "Premium Celebration Box",
    description: "Luxury dessert assortment.",
    itemsToBox: 5,
    price: 1200,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "28-3", title: "Party Boxes"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),

  // ===== BREADS (39-x) =====
  Product(
    id: "P29",
    title: "Classic White Bread Loaf",
    description: "Soft daily white bread.",
    itemsToBox: 5,
    price: 25,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "39-1", title: "White Bread"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P30",
    title: "Whole Wheat Bread",
    description: "Healthy whole wheat loaf.",
    itemsToBox: 5,
    price: 30,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "39-2", title: "Whole Wheat Bread"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P31",
    title: "Sourdough Bread",
    description: "Artisan sourdough loaf.",
    itemsToBox: 5,
    price: 55,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "39-3", title: "Artisan Bread"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
  Product(
    id: "P32",
    title: "Multigrain Bread",
    description: "Nutritious multigrain bread.",
    itemsToBox: 5,
    price: 40,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "39-3", title: "Artisan Bread"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),

  // ===== CROISSANTS (17-x) =====
  Product(
    id: "P33",
    title: "Butter Croissant",
    description: "Flaky buttery croissant.",
    itemsToBox: 5,
    price: 35,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "17-1", title: "Butter Croissants"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P34",
    title: "Chocolate Croissant",
    description: "Croissant filled with chocolate.",
    itemsToBox: 5,
    price: 45,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(
      id: "17-2",
      title: "Chocolate Croissants",
    ),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P35",
    title: "Almond Croissant",
    description: "Croissant topped with almonds.",
    itemsToBox: 5,
    price: 50,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "17-3", title: "Almond Croissants"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P36",
    title: "Mini Croissant Box",
    description: "Box of mini croissants.",
    itemsToBox: 5,
    price: 220,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "17-1", title: "Butter Croissants"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),

  // ===== TRADITIONAL SWEETS (11-x) =====
  Product(
    id: "P37",
    title: "Basbousa Tray",
    description: "Traditional semolina dessert.",
    itemsToBox: 5,
    price: 320,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "11-1", title: "Basbousa"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
  Product(
    id: "P38",
    title: "Kunafa with Cream",
    description: "Golden kunafa filled with cream.",
    itemsToBox: 5,
    price: 400,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "11-2", title: "Kunafa"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
  Product(
    id: "P39",
    title: "Baklava Assorted Box",
    description: "Mixed nuts baklava.",
    itemsToBox: 5,
    price: 550,
    discount: 1,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "11-3", title: "Baklava"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
  Product(
    id: "P40",
    title: "Kunafa Nutella",
    description: "Kunafa stuffed with Nutella.",
    itemsToBox: 5,
    price: 450,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "11-2", title: "Kunafa"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),

  // ===== FROZEN DESSERTS (23-x) =====
  Product(
    id: "P41",
    title: "Vanilla Ice Cream Tub",
    description: "Creamy vanilla ice cream.",
    itemsToBox: 5,
    price: 120,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "23-1", title: "Ice Cream"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P42",
    title: "Chocolate Gelato",
    description: "Italian style chocolate gelato.",
    itemsToBox: 5,
    price: 150,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "23-2", title: "Gelato"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P43",
    title: "Ice Cream Cake",
    description: "Vanilla and chocolate ice cream cake.",
    itemsToBox: 5,
    price: 600,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "23-3", title: "Ice Cream Cakes"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: false,
  ),
  Product(
    id: "P44",
    title: "Strawberry Gelato",
    description: "Fresh strawberry gelato.",
    itemsToBox: 5,
    price: 150,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "23-2", title: "Gelato"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),

  // ===== SEASONAL (89-x) =====
  Product(
    id: "P45",
    title: "Ramadan Kunafa Box",
    description: "Special Ramadan dessert box.",
    itemsToBox: 5,
    price: 900,
    discount: 15,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "89-1", title: "Ramadan Specials"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
  Product(
    id: "P46",
    title: "Christmas Cake Special",
    description: "Festive Christmas cake.",
    itemsToBox: 5,
    price: 1000,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "89-2", title: "Christmas Specials"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
  Product(
    id: "P47",
    title: "Valentine Chocolate Hearts",
    description: "Heart-shaped chocolate box.",
    itemsToBox: 5,
    price: 700,
    discount: null,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "89-3", title: "Valentine Specials"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
  Product(
    id: "P48",
    title: "Eid Dessert Collection",
    description: "Special Eid assorted sweets.",
    itemsToBox: 5,
    price: 1100,
    discount: 12,
    images: null,
    thumbnail: null,
    subCategoryId: ProductSubCategory(id: "89-1", title: "Ramadan Specials"),
    cover: null,
    enabled: true,
    taxAverage: 14,
    enabledImageAttachment: true,
  ),
];

// final List<Product> englishProducts = [
//   Product(
//     id: "1",
//     title: "Bluberry Cheese Cake Jar ",
//     description: "A lightweight moisturizer for daily hydration.",
//     images: ["lib/assets/productsImages/Bluberry Cheese Cake Jar.png"],
//     price: 12.99,
//     categoryId: "Beauty",
//     video: "",
//   ),
//   Product(
//     id: "2",
//     title: "Caramel Tartelette",
//     description: "Brightening serum for glowing skin.",
//     images: ["lib/assets/productsImages/Caramel Tartelette.png"],
//     price: 18.50,
//     categoryId: "Beauty",
//     video: "",
//   ),
//   Product(
//     id: "3",
//     title: "Chocolate Hazelnut Cake",
//     description: "Premium-quality 12-piece makeup brush set.",
//     images: ["lib/assets/productsImages/Chocolate Hazelnut Cake.png"],
//     price: 22.00,
//     categoryId: "Beauty",
//     video: "",
//   ),
//   Product(
//     id: "4",
//     title: "Dark Fudge Cake",
//     description: "Premium-quality 12-piece makeup brush set.",
//     images: ["lib/assets/productsImages/Dark Fudge Cake.png"],
//     price: 22.00,
//     categoryId: "Beauty",
//     video: "",
//   ),
//   Product(
//     id: "5",
//     title: "Hazelnut Ganache Tartelette",
//     description: "Premium-quality 12-piece makeup brush set.",
//     images: ["lib/assets/productsImages/Hazelnut Ganache Tartelette.png"],
//     price: 22.00,
//     categoryId: "Beauty",
//     video: "",
//   ),
//   Product(
//     id: "6",
//     title: "Hazelnut Oven Molten Cake",
//     description: "Premium-quality 12-piece makeup brush set.",
//     images: ["lib/assets/productsImages/Hazelnut Oven Molten Cake.png"],
//     price: 22.00,
//     categoryId: "Beauty",
//     video: "",
//   ),

//   // Fragrances (4–6)
//   Product(
//     id: "7",
//     title: "Honey Cake Honey Cake Honey Cake",
//     description: "Fresh aquatic fragrance for daily wear.",
//     images: ["lib/assets/productsImages/Honey Cake.png"],
//     price: 35.00,
//     categoryId: "Fragrances",
//     video: "",
//   ),
//   Product(
//     id: "8",
//     title: "Kinder Tartelette",
//     description: "Warm woody scent with amber undertones.",
//     images: ["lib/assets/productsImages/Kinder Tartelette.png"],
//     price: 49.99,
//     categoryId: "Fragrances",
//     video: "",
//   ),
//   Product(
//     id: "9",
//     title: "Lotus Jar",
//     description: "Light floral body mist with long-lasting freshness.",
//     images: ["lib/assets/productsImages/Lotus Jar.png"],
//     price: 14.99,
//     categoryId: "Fragrances",
//     video: "",
//   ),
//   Product(
//     id: "10",
//     title: "Maltesers Cake",
//     description: "Light floral body mist with long-lasting freshness.",
//     images: ["lib/assets/productsImages/Maltesers Cake.png"],
//     price: 14.99,
//     categoryId: "Fragrances",
//     video: "",
//   ),
//   Product(
//     id: "11",
//     title: "Marble English Cake",
//     description: "Light floral body mist with long-lasting freshness.",
//     images: ["lib/assets/productsImages/Marble English Cake.png"],
//     price: 14.99,
//     categoryId: "Fragrances",
//     video: "",
//   ),
//   Product(
//     id: "12",
//     title: "Mars Tartelette",
//     description: "Light floral body mist with long-lasting freshness.",
//     images: ["lib/assets/productsImages/Mars Tartelette.png"],
//     price: 14.99,
//     categoryId: "Fragrances",
//     video: "",
//   ),

//   // Furniture (7–9)
//   Product(
//     id: "13",
//     title: "Mini Bluberry Cheese Cake",
//     description: "Three-seater fabric sofa with wooden legs.",
//     images: ["lib/assets/productsImages/Mini Bluberry Cheese Cake.png"],
//     price: 450.00,
//     categoryId: "Furniture",
//     video: "",
//   ),
//   Product(
//     id: "1400",
//     title: "Mini Caramel Cheese Cake",
//     description: "Minimalist coffee table made of oak wood.",
//     images: ["lib/assets/productsImages/Mini Caramel Cheese Cake.png"],
//     price: 120.00,
//     categoryId: "Furniture",
//     video: "",
//   ),
//   Product(
//     id: "14",
//     title: "Mini Caramel Fudge",
//     description: "Ergonomic chair with adjustable height and back support.",
//     images: ["lib/assets/productsImages/Mini Caramel Fudge.png"],
//     price: 99.99,
//     categoryId: "Furniture",
//     video: "",
//   ),
//   Product(
//     id: "15",
//     title: "Mini Chocolate Lovers",
//     description: "Ergonomic chair with adjustable height and back support.",
//     images: ["lib/assets/productsImages/Mini Chocolate Lovers.png"],
//     price: 99.99,
//     categoryId: "Furniture",
//     video: "",
//   ),
//   Product(
//     id: "16",
//     title: "Mini Coffee Mousse",
//     description: "Ergonomic chair with adjustable height and back support.",
//     images: ["lib/assets/productsImages/Mini Coffee Mousse.png"],
//     price: 99.99,
//     categoryId: "Furniture",
//     video: "",
//   ),
//   Product(
//     id: "17",
//     title: "Mini Flutes",
//     description: "Ergonomic chair with adjustable height and back support.",
//     images: ["lib/assets/productsImages/Mini Flutes.png"],
//     price: 99.99,
//     categoryId: "Furniture",
//     video: "",
//   ),

//   // Groceries (10–12)
//   Product(
//     id: "18",
//     title: "Mini KitKat",
//     description: "1kg pack of healthy organic brown rice.",
//     images: ["lib/assets/productsImages/Mini KitKat.png"],
//     price: 5.99,
//     categoryId: "Groceries",
//     video: "",
//   ),
//   Product(
//     id: "19",
//     title: "Mini Lotus Molten Cake",
//     description: "Cold-pressed olive oil, 500ml bottle.",
//     images: ["lib/assets/productsImages/Mini Lotus Molten Cake.png"],
//     price: 8.99,
//     categoryId: "Groceries",
//     video: "",
//   ),
//   Product(
//     id: "20",
//     title: "Mini Nutella Cheese Cake",
//     description: "Premium roasted coffee beans, 1kg.",
//     images: ["lib/assets/productsImages/Mini Nutella Cheese Cake.png"],
//     price: 15.50,
//     categoryId: "Groceries",
//     video: "",
//   ),
//   Product(
//     id: "21",
//     title: "Mini Quatra",
//     description: "Premium roasted coffee beans, 1kg.",
//     images: ["lib/assets/productsImages/Mini Quatra.png"],
//     price: 15.50,
//     categoryId: "Groceries",
//     video: "",
//   ),
//   Product(
//     id: "22",
//     title: "Mini Strawberry Cheese Cake",
//     description: "Premium roasted coffee beans, 1kg.",
//     images: ["lib/assets/productsImages/Mini Strawberry Cheese Cake.png"],
//     price: 15.50,
//     categoryId: "Groceries",
//     video: "",
//   ),
//   Product(
//     id: "23",
//     title: "Nutella Tartelette",
//     description: "Premium roasted coffee beans, 1kg.",
//     images: ["lib/assets/productsImages/Nutella Tartelette.png"],
//     price: 15.50,
//     categoryId: "Groceries",
//     video: "",
//   ),

//   // Home Decoration (13–15)
//   Product(
//     id: "24",
//     title: "pananna",
//     description: "Minimalist modern abstract painting.",
//     images: ["lib/assets/productsImages/pananna.png"],
//     price: 40.00,
//     categoryId: "Home Decoration",
//     video: "",
//   ),
//   Product(
//     id: "25",
//     title: "Red Velvet Jar",
//     description: "Ceramic vase with glossy finish.",
//     images: ["lib/assets/productsImages/Red Velvet Jar.png"],
//     price: 25.00,
//     categoryId: "Home Decoration",
//     video: "",
//   ),
//   Product(
//     id: "26",
//     title: "Snickers Tartelette",
//     description: "Warm white decorative string lights.",
//     images: ["lib/assets/productsImages/Snickers Tartelette.png"],
//     price: 12.00,
//     categoryId: "Home Decoration",
//     video: "",
//   ),
//   Product(
//     id: "27",
//     title: "Vienna 22 Sesame",
//     description: "Warm white decorative string lights.",
//     images: ["lib/assets/productsImages/Vienna 22 Sesame.png"],
//     price: 12.00,
//     categoryId: "Home Decoration",
//     video: "",
//   ),
//   Product(
//     id: "28",
//     title: "Decorative Wall Mirror",
//     description: "Warm white decorative string lights.",
//     images: [],
//     price: 12.00,
//     categoryId: "Home Decoration",
//     video: "",
//   ),
//   Product(
//     id: "29",
//     title: "Scented Candles Set",
//     description: "Warm white decorative string lights.",
//     images: [],
//     price: 12.00,
//     categoryId: "Home Decoration",
//     video: "",
//   ),

//   // Kitchen Accessories (16–18)
//   Product(
//     id: "30",
//     title: "Stainless Steel Knife Set",
//     description: "5-piece premium kitchen knife set.",
//     images: [],
//     price: 32.00,
//     categoryId: "Kitchen Accessories",
//     video: "",
//   ),
//   Product(
//     id: "31",
//     title: "Non-stick Frying Pan",
//     description: "Durable 28cm frying pan with ceramic coating.",
//     images: [],
//     price: 18.99,
//     categoryId: "Kitchen Accessories",
//     video: "",
//   ),
//   Product(
//     id: "32",
//     title: "Glass Food Containers",
//     description: "Set of 6 airtight food storage containers.",
//     images: [],
//     price: 20.00,
//     categoryId: "Kitchen Accessories",
//     video: "",
//   ),
//   Product(
//     id: "33",
//     title: "Silicone Baking Mat",
//     description: "Set of 6 airtight food storage containers.",
//     images: [],
//     price: 20.00,
//     categoryId: "Kitchen Accessories",
//     video: "",
//   ),
//   Product(
//     id: "34",
//     title: "Electric Kettle",
//     description: "Set of 6 airtight food storage containers.",
//     images: [],
//     price: 20.00,
//     categoryId: "Kitchen Accessories",
//     video: "",
//   ),
//   Product(
//     id: "35",
//     title: "Measuring Cups Set",
//     description: "Set of 6 airtight food storage containers.",
//     images: [],
//     price: 20.00,
//     categoryId: "Kitchen Accessories",
//     video: "",
//   ),

//   // Laptops (19–21)
//   Product(
//     id: "36",
//     title: "Ultrabook Pro 14",
//     description: "Slim 14-inch laptop with 16GB RAM.",
//     images: [],
//     price: 899.00,
//     categoryId: "Laptops",
//     video: "",
//   ),
//   Product(
//     id: "37",
//     title: "Gaming Laptop X",
//     description: "High-performance laptop with RTX graphics.",
//     images: [],
//     price: 1299.00,
//     categoryId: "Laptops",
//     video: "",
//   ),
//   Product(
//     id: "38",
//     title: "Lightweight Notebook",
//     description: "Portable notebook ideal for students.",
//     images: [],
//     price: 550.00,
//     categoryId: "Laptops",
//     video: "",
//   ),
//   Product(
//     id: "39",
//     title: "Business Laptop Pro",
//     description: "Portable notebook ideal for students.",
//     images: [],
//     price: 550.00,
//     categoryId: "Laptops",
//     video: "",
//   ),
//   Product(
//     id: "40",
//     title: "Student Laptop 15",
//     description: "Portable notebook ideal for students.",
//     images: [],
//     price: 550.00,
//     categoryId: "Laptops",
//     video: "",
//   ),
//   Product(
//     id: "41",
//     title: "Convertible 2-in-1 Laptop",
//     description: "Portable notebook ideal for students.",
//     images: [],
//     price: 550.00,
//     categoryId: "Laptops",
//     video: "",
//   ),

//   // Mens Shirts (22–24)
//   Product(
//     id: "42",
//     title: "Casual Cotton Shirt",
//     description: "Slim-fit cotton shirt for daily wear.",
//     images: [],
//     price: 19.99,
//     categoryId: "Mens Shirts",
//     video: "",
//   ),
//   Product(
//     id: "43",
//     title: "Formal White Shirt",
//     description: "Classic white shirt for formal occasions.",
//     images: [],
//     price: 25.00,
//     categoryId: "Mens Shirts",
//     video: "",
//   ),
//   Product(
//     id: "44",
//     title: "Plaid Flannel Shirt",
//     description: "Warm flannel shirt with plaid design.",
//     images: [],
//     price: 22.50,
//     categoryId: "Mens Shirts",
//     video: "",
//   ),
//   Product(
//     id: "45",
//     title: "Striped Polo Shirt",
//     description: "Warm flannel shirt with plaid design.",
//     images: [],
//     price: 22.50,
//     categoryId: "Mens Shirts",
//     video: "",
//   ),
//   Product(
//     id: "46",
//     title: "Denim Button Shirt",
//     description: "Warm flannel shirt with plaid design.",
//     images: [],
//     price: 22.50,
//     categoryId: "Mens Shirts",
//     video: "",
//   ),
//   Product(
//     id: "47",
//     title: "Linen Summer Shirt",
//     description: "Warm flannel shirt with plaid design.",
//     images: [],
//     price: 22.50,
//     categoryId: "Mens Shirts",
//     video: "",
//   ),

//   // Mens Shoes (25–27)
//   Product(
//     id: "48",
//     title: "Running Sneakers",
//     description: "Breathable sports sneakers for men.",
//     images: [],
//     price: 55.00,
//     categoryId: "Mens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "49",
//     title: "Leather Boots",
//     description: "Durable brown leather boots.",
//     images: [],
//     price: 89.00,
//     categoryId: "Mens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "50",
//     title: "Casual Loafers",
//     description: "Comfortable loafers suitable for daily wear.",
//     images: [],
//     price: 45.00,
//     categoryId: "Mens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "51",
//     title: "Formal Dress Shoes",
//     description: "Comfortable loafers suitable for daily wear.",
//     images: [],
//     price: 45.00,
//     categoryId: "Mens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "52",
//     title: "Canvas Slip-Ons",
//     description: "Comfortable loafers suitable for daily wear.",
//     images: [],
//     price: 45.00,
//     categoryId: "Mens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "53",
//     title: "High-Top Trainers",
//     description: "Comfortable loafers suitable for daily wear.",
//     images: [],
//     price: 45.00,
//     categoryId: "Mens Shoes",
//     video: "",
//   ),

//   // Mens Watches (28–30)
//   Product(
//     id: "54",
//     title: "Analog Leather Watch",
//     description: "Classic analog watch with leather strap.",
//     images: [],
//     price: 60.00,
//     categoryId: "Mens Watches",
//     video: "",
//   ),
//   Product(
//     id: "55",
//     title: "Steel Wrist Watch",
//     description: "Stainless steel men’s watch with date feature.",
//     images: [],
//     price: 75.00,
//     categoryId: "Mens Watches",
//     video: "",
//   ),
//   Product(
//     id: "56",
//     title: "Digital Sports Watch",
//     description: "Waterproof digital watch with stopwatch.",
//     images: [],
//     price: 35.00,
//     categoryId: "Mens Watches",
//     video: "",
//   ),
//   Product(
//     id: "57",
//     title: "Chronograph Watch",
//     description: "Waterproof digital watch with stopwatch.",
//     images: [],
//     price: 35.00,
//     categoryId: "Mens Watches",
//     video: "",
//   ),
//   Product(
//     id: "58",
//     title: "Minimalist Black Watch",
//     description: "Waterproof digital watch with stopwatch.",
//     images: [],
//     price: 35.00,
//     categoryId: "Mens Watches",
//     video: "",
//   ),
//   Product(
//     id: "59",
//     title: "Silver Dress Watch",
//     description: "Waterproof digital watch with stopwatch.",
//     images: [],
//     price: 35.00,
//     categoryId: "Mens Watches",
//     video: "",
//   ),

//   // Mobile Accessories (31–33)
//   Product(
//     id: "60",
//     title: "Fast Charging Cable",
//     description: "USB-C fast charging cable, 1m.",
//     images: [],
//     price: 5.99,
//     categoryId: "Mobile Accessories",
//     video: "",
//   ),
//   Product(
//     id: "61",
//     title: "Wireless Charger",
//     description: "Qi-certified wireless charging pad.",
//     images: [],
//     price: 19.99,
//     categoryId: "Mobile Accessories",
//     video: "",
//   ),
//   Product(
//     id: "62",
//     title: "Phone Tripod",
//     description: "Compact tripod for smartphones.",
//     images: [],
//     price: 12.00,
//     categoryId: "Mobile Accessories",
//     video: "",
//   ),
//   Product(
//     id: "63",
//     title: "Screen Protector Pack",
//     description: "Compact tripod for smartphones.",
//     images: [],
//     price: 12.00,
//     categoryId: "Mobile Accessories",
//     video: "",
//   ),
//   Product(
//     id: "64",
//     title: "Phone Case",
//     description: "Compact tripod for smartphones.",
//     images: [],
//     price: 12.00,
//     categoryId: "Mobile Accessories",
//     video: "",
//   ),
//   Product(
//     id: "65",
//     title: "Car Charger Adapter",
//     description: "Compact tripod for smartphones.",
//     images: [],
//     price: 12.00,
//     categoryId: "Mobile Accessories",
//     video: "",
//   ),

//   // Motorcycle (34–36)
//   Product(
//     id: "66",
//     title: "Motorcycle Helmet",
//     description: "High-quality full-face helmet.",
//     images: [],
//     price: 85.00,
//     categoryId: "Motorcycle",
//     video: "",
//   ),
//   Product(
//     id: "67",
//     title: "Riding Gloves",
//     description: "Protective gloves for bikers.",
//     images: [],
//     price: 20.00,
//     categoryId: "Motorcycle",
//     video: "",
//   ),
//   Product(
//     id: "68",
//     title: "Bike Phone Holder",
//     description: "Durable mobile phone mount for bikes.",
//     images: [],
//     price: 10.00,
//     categoryId: "Motorcycle",
//     video: "",
//   ),
//   Product(
//     id: "69",
//     title: "Reflective Safety Vest",
//     description: "Durable mobile phone mount for bikes.",
//     images: [],
//     price: 10.00,
//     categoryId: "Motorcycle",
//     video: "",
//   ),
//   Product(
//     id: "70",
//     title: "Motorbike Cover",
//     description: "Durable mobile phone mount for bikes.",
//     images: [],
//     price: 10.00,
//     categoryId: "Motorcycle",
//     video: "",
//   ),
//   Product(
//     id: "71",
//     title: "LED Bike Lights",
//     description: "Durable mobile phone mount for bikes.",
//     images: [],
//     price: 10.00,
//     categoryId: "Motorcycle",
//     video: "",
//   ),

//   // Skin Care (37–39)
//   Product(
//     id: "72",
//     title: "Aloe Vera Gel",
//     description: "Soothing gel for skin hydration.",
//     images: [],
//     price: 9.99,
//     categoryId: "Skin Care",
//     video: "",
//   ),
//   Product(
//     id: "73",
//     title: "Sunscreen SPF 50",
//     description: "Broad-spectrum sun protection.",
//     images: [],
//     price: 14.50,
//     categoryId: "Skin Care",
//     video: "",
//   ),
//   Product(
//     id: "74",
//     title: "Foaming Face Wash",
//     description: "Gentle cleanser for daily use.",
//     images: [],
//     price: 7.99,
//     categoryId: "Skin Care",
//     video: "",
//   ),
//   Product(
//     id: "75",
//     title: "Charcoal Face Mask",
//     description: "Gentle cleanser for daily use.",
//     images: [],
//     price: 7.99,
//     categoryId: "Skin Care",
//     video: "",
//   ),
//   Product(
//     id: "76",
//     title: "Hydrating Toner",
//     description: "Gentle cleanser for daily use.",
//     images: [],
//     price: 7.99,
//     categoryId: "Skin Care",
//     video: "",
//   ),
//   Product(
//     id: "77",
//     title: "Anti-Aging Cream",
//     description: "Gentle cleanser for daily use.",
//     images: [],
//     price: 7.99,
//     categoryId: "Skin Care",
//     video: "",
//   ),

//   // Smartphones (40–42)
//   Product(
//     id: "78",
//     title: "Smartphone X12",
//     description: "6.5-inch smartphone with great battery life.",
//     images: [],
//     price: 450.00,
//     categoryId: "Smartphones",
//     video: "",
//   ),
//   Product(
//     id: "79",
//     title: "Smartphone Nova A9",
//     description: "Mid-range phone with excellent camera.",
//     images: [],
//     price: 320.00,
//     categoryId: "Smartphones",
//     video: "",
//   ),
//   Product(
//     id: "80",
//     title: "Smartphone Mini Lite",
//     description: "Compact smartphone with fast charging.",
//     images: [],
//     price: 219.00,
//     categoryId: "Smartphones",
//     video: "",
//   ),
//   Product(
//     id: "81",
//     title: "Smartphone Pro Max",
//     description: "Compact smartphone with fast charging.",
//     images: [],
//     price: 219.00,
//     categoryId: "Smartphones",
//     video: "",
//   ),
//   Product(
//     id: "82",
//     title: "Budget Smartphone Z5",
//     description: "Compact smartphone with fast charging.",
//     images: [],
//     price: 219.00,
//     categoryId: "Smartphones",
//     video: "",
//   ),
//   Product(
//     id: "83",
//     title: "Foldable Smartphone F1",
//     description: "Compact smartphone with fast charging.",
//     images: [],
//     price: 219.00,
//     categoryId: "Smartphones",
//     video: "",
//   ),

//   // Sports Accessories (43–45)
//   Product(
//     id: "84",
//     title: "Fitness Resistance Bands",
//     description: "Set of 5 resistance bands for workouts.",
//     images: [],
//     price: 15.00,
//     categoryId: "Sports Accessories",
//     video: "",
//   ),
//   Product(
//     id: "85",
//     title: "Football",
//     description: "Professional match-quality football.",
//     images: [],
//     price: 25.00,
//     categoryId: "Sports Accessories",
//     video: "",
//   ),
//   Product(
//     id: "86",
//     title: "Yoga Mat",
//     description: "Non-slip 6mm yoga mat.",
//     images: [],
//     price: 18.99,
//     categoryId: "Sports Accessories",
//     video: "",
//   ),
//   Product(
//     id: "87",
//     title: "Dumbbell Set",
//     description: "Non-slip 6mm yoga mat.",
//     images: [],
//     price: 18.99,
//     categoryId: "Sports Accessories",
//     video: "",
//   ),
//   Product(
//     id: "88",
//     title: "Jump Rope",
//     description: "Non-slip 6mm yoga mat.",
//     images: [],
//     price: 18.99,
//     categoryId: "Sports Accessories",
//     video: "",
//   ),
//   Product(
//     id: "89",
//     title: "Exercise Ball",
//     description: "Non-slip 6mm yoga mat.",
//     images: [],
//     price: 18.99,
//     categoryId: "Sports Accessories",
//     video: "",
//   ),

//   // Sunglasses (46–48)
//   Product(
//     id: "90",
//     title: "Aviator Sunglasses",
//     description: "Classic metal-frame aviators.",
//     images: [],
//     price: 30.00,
//     categoryId: "Sunglasses",
//     video: "",
//   ),
//   Product(
//     id: "91",
//     title: "Polarized Driving Sunglasses",
//     description: "Anti-glare polarized lenses.",
//     images: [],
//     price: 22.00,
//     categoryId: "Sunglasses",
//     video: "",
//   ),
//   Product(
//     id: "92",
//     title: "Sports Sunglasses",
//     description: "Lightweight wraparound sports glasses.",
//     images: [],
//     price: 18.00,
//     categoryId: "Sunglasses",
//     video: "",
//   ),
//   Product(
//     id: "93",
//     title: "Round Frame Sunglasses",
//     description: "Lightweight wraparound sports glasses.",
//     images: [],
//     price: 18.00,
//     categoryId: "Sunglasses",
//     video: "",
//   ),
//   Product(
//     id: "94",
//     title: "Cat Eye Sunglasses",
//     description: "Lightweight wraparound sports glasses.",
//     images: [],
//     price: 18.00,
//     categoryId: "Sunglasses",
//     video: "",
//   ),
//   Product(
//     id: "95",
//     title: "Mirror Lens Sunglasses",
//     description: "Lightweight wraparound sports glasses.",
//     images: [],
//     price: 18.00,
//     categoryId: "Sunglasses",
//     video: "",
//   ),

//   // Tablets (49–51)
//   Product(
//     id: "96",
//     title: "Tablet Pro 10",
//     description: "10-inch professional productivity tablet.",
//     images: [],
//     price: 499.00,
//     categoryId: "Tablets",
//     video: "",
//   ),
//   Product(
//     id: "97",
//     title: "Kids Learning Tablet",
//     description: "Durable educational tablet for kids.",
//     images: [],
//     price: 150.00,
//     categoryId: "Tablets",
//     video: "",
//   ),
//   Product(
//     id: "98",
//     title: "Compact Media Tablet",
//     description: "8-inch tablet for entertainment.",
//     images: [],
//     price: 179.00,
//     categoryId: "Tablets",
//     video: "",
//   ),
//   Product(
//     id: "99",
//     title: "Drawing Tablet X",
//     description: "8-inch tablet for entertainment.",
//     images: [],
//     price: 179.00,
//     categoryId: "Tablets",
//     video: "",
//   ),
//   Product(
//     id: "100",
//     title: "Business Tablet 12",
//     description: "8-inch tablet for entertainment.",
//     images: [],
//     price: 179.00,
//     categoryId: "Tablets",
//     video: "",
//   ),
//   Product(
//     id: "101",
//     title: "Mini Tablet 7",
//     description: "8-inch tablet for entertainment.",
//     images: [],
//     price: 179.00,
//     categoryId: "Tablets",
//     video: "",
//   ),

//   // Tops (52–54)
//   Product(
//     id: "102",
//     title: "Cotton Casual Top",
//     description: "Soft cotton top for women.",
//     images: [],
//     price: 12.00,
//     categoryId: "Tops",
//     video: "",
//   ),
//   Product(
//     id: "103",
//     title: "Sleeveless Tank Top",
//     description: "Lightweight summer tank top.",
//     images: [],
//     price: 8.99,
//     categoryId: "Tops",
//     video: "",
//   ),
//   Product(
//     id: "104",
//     title: "Long Sleeve Blouse",
//     description: "Elegant blouse for casual outings.",
//     images: [],
//     price: 18.00,
//     categoryId: "Tops",
//     video: "",
//   ),
//   Product(
//     id: "105",
//     title: "Printed Crop Top",
//     description: "Elegant blouse for casual outings.",
//     images: [],
//     price: 18.00,
//     categoryId: "Tops",
//     video: "",
//   ),
//   Product(
//     id: "106",
//     title: "Knitted Sweater",
//     description: "Elegant blouse for casual outings.",
//     images: [],
//     price: 18.00,
//     categoryId: "Tops",
//     video: "",
//   ),
//   Product(
//     id: "107",
//     title: "Silk Camisole",
//     description: "Elegant blouse for casual outings.",
//     images: [],
//     price: 18.00,
//     categoryId: "Tops",
//     video: "",
//   ),

//   // Vehicle (55–57)
//   Product(
//     id: "108",
//     title: "Car Vacuum Cleaner",
//     description: "Portable vacuum cleaner for vehicles.",
//     images: [],
//     price: 25.00,
//     categoryId: "Vehicle",
//     video: "",
//   ),
//   Product(
//     id: "109",
//     title: "Car Dashboard Perfume",
//     description: "Long-lasting gel perfume for cars.",
//     images: [],
//     price: 6.50,
//     categoryId: "Vehicle",
//     video: "",
//   ),
//   Product(
//     id: "110",
//     title: "Car Phone Holder",
//     description: "Rotating dashboard phone mount.",
//     images: [],
//     price: 9.99,
//     categoryId: "Vehicle",
//     video: "",
//   ),
//   Product(
//     id: "111",
//     title: "Car Seat Organizer",
//     description: "Rotating dashboard phone mount.",
//     images: [],
//     price: 9.99,
//     categoryId: "Vehicle",
//     video: "",
//   ),
//   Product(
//     id: "112",
//     title: "Car Sunshade",
//     description: "Rotating dashboard phone mount.",
//     images: [],
//     price: 9.99,
//     categoryId: "Vehicle",
//     video: "",
//   ),
//   Product(
//     id: "113",
//     title: "Car Jump Starter",
//     description: "Rotating dashboard phone mount.",
//     images: [],
//     price: 9.99,
//     categoryId: "Vehicle",
//     video: "",
//   ),

//   // Womens Bags (58–60)
//   Product(
//     id: "114",
//     title: "Leather Handbag",
//     description: "Elegant premium leather handbag.",
//     images: [],
//     price: 65.00,
//     categoryId: "Womens Bags",
//     video: "",
//   ),
//   Product(
//     id: "115",
//     title: "Crossbody Bag",
//     description: "Lightweight crossbody bag.",
//     images: [],
//     price: 32.00,
//     categoryId: "Womens Bags",
//     video: "",
//   ),
//   Product(
//     id: "116",
//     title: "Travel Tote Bag",
//     description: "Large durable tote for travel.",
//     images: [],
//     price: 40.00,
//     categoryId: "Womens Bags",
//     video: "",
//   ),
//   Product(
//     id: "117",
//     title: "Mini Shoulder Bag",
//     description: "Large durable tote for travel.",
//     images: [],
//     price: 40.00,
//     categoryId: "Womens Bags",
//     video: "",
//   ),
//   Product(
//     id: "118",
//     title: "Clutch Bag",
//     description: "Large durable tote for travel.",
//     images: [],
//     price: 40.00,
//     categoryId: "Womens Bags",
//     video: "",
//   ),
//   Product(
//     id: "119",
//     title: "Backpack Purse",
//     description: "Large durable tote for travel.",
//     images: [],
//     price: 40.00,
//     categoryId: "Womens Bags",
//     video: "",
//   ),

//   // Womens Dresses (61–63)
//   Product(
//     id: "120",
//     title: "Floral Summer Dress",
//     description: "Light and comfortable floral dress.",
//     images: [],
//     price: 28.00,
//     categoryId: "Womens Dresses",
//     video: "",
//   ),
//   Product(
//     id: "121",
//     title: "Evening Gown",
//     description: "Elegant long gown for special events.",
//     images: [],
//     price: 75.00,
//     categoryId: "Womens Dresses",
//     video: "",
//   ),
//   Product(
//     id: "122",
//     title: "Casual Midi Dress",
//     description: "Comfortable midi-length dress.",
//     images: [],
//     price: 30.00,
//     categoryId: "Womens Dresses",
//     video: "",
//   ),
//   Product(
//     id: "123",
//     title: "Bodycon Dress",
//     description: "Comfortable midi-length dress.",
//     images: [],
//     price: 30.00,
//     categoryId: "Womens Dresses",
//     video: "",
//   ),
//   Product(
//     id: "124",
//     title: "Maxi Dress",
//     description: "Comfortable midi-length dress.",
//     images: [],
//     price: 30.00,
//     categoryId: "Womens Dresses",
//     video: "",
//   ),
//   Product(
//     id: "125",
//     title: "Shirt Dress",
//     description: "Comfortable midi-length dress.",
//     images: [],
//     price: 30.00,
//     categoryId: "Womens Dresses",
//     video: "",
//   ),

//   // Womens Jewellery (64–66)
//   Product(
//     id: "126",
//     title: "Gold-Plated Necklace",
//     description: "Beautiful gold-plated necklace.",
//     images: [],
//     price: 20.00,
//     categoryId: "Womens Jewellery",
//     video: "",
//   ),
//   Product(
//     id: "127",
//     title: "Silver Bracelet",
//     description: "Elegant sterling silver bracelet.",
//     images: [],
//     price: 18.00,
//     categoryId: "Womens Jewellery",
//     video: "",
//   ),
//   Product(
//     id: "128",
//     title: "Diamond Stud Earrings",
//     description: "Classic diamond stud earrings.",
//     images: [],
//     price: 49.00,
//     categoryId: "Womens Jewellery",
//     video: "",
//   ),
//   Product(
//     id: "129",
//     title: "Pearl Pendant Necklace",
//     description: "Classic diamond stud earrings.",
//     images: [],
//     price: 49.00,
//     categoryId: "Womens Jewellery",
//     video: "",
//   ),
//   Product(
//     id: "130",
//     title: "Charm Bracelet",
//     description: "Classic diamond stud earrings.",
//     images: [],
//     price: 49.00,
//     categoryId: "Womens Jewellery",
//     video: "",
//   ),
//   Product(
//     id: "131",
//     title: "Hoop Earrings Set",
//     description: "Classic diamond stud earrings.",
//     images: [],
//     price: 49.00,
//     categoryId: "Womens Jewellery",
//     video: "",
//   ),

//   // Womens Shoes (67–69)
//   Product(
//     id: "132",
//     title: "High Heels",
//     description: "Stylish high heels for parties.",
//     images: [],
//     price: 35.00,
//     categoryId: "Womens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "133",
//     title: "Running Shoes",
//     description: "Comfortable running shoes for women.",
//     images: [],
//     price: 50.00,
//     categoryId: "Womens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "134",
//     title: "Casual Flats",
//     description: "Lightweight everyday flat shoes.",
//     images: [],
//     price: 22.00,
//     categoryId: "Womens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "135",
//     title: "Ankle Boots",
//     description: "Lightweight everyday flat shoes.",
//     images: [],
//     price: 22.00,
//     categoryId: "Womens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "136",
//     title: "Sandals",
//     description: "Lightweight everyday flat shoes.",
//     images: [],
//     price: 22.00,
//     categoryId: "Womens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "137",
//     title: "Ballet Flats",
//     description: "Lightweight everyday flat shoes.",
//     images: [],
//     price: 22.00,
//     categoryId: "Womens Shoes",
//     video: "",
//   ),

//   // Womens Watches (70)
//   Product(
//     id: "138",
//     title: "Rose Gold Watch",
//     description: "Stylish rose gold wristwatch for women.",
//     images: [],
//     price: 55.00,
//     categoryId: "Womens Watches",
//     video: "",
//   ),
//   Product(
//     id: "139",
//     title: "Silver Bracelet Watch",
//     description: "Stylish rose gold wristwatch for women.",
//     images: [],
//     price: 55.00,
//     categoryId: "Womens Watches",
//     video: "",
//   ),
//   Product(
//     id: "140",
//     title: "Digital Fitness Watch",
//     description: "Stylish rose gold wristwatch for women.",
//     images: [],
//     price: 55.00,
//     categoryId: "Womens Watches",
//     video: "",
//   ),
//   Product(
//     id: "141",
//     title: "Leather Strap Watch",
//     description: "Stylish rose gold wristwatch for women.",
//     images: [],
//     price: 55.00,
//     categoryId: "Womens Watches",
//     video: "",
//   ),
//   Product(
//     id: "142",
//     title: "Minimalist White Watch",
//     description: "Stylish rose gold wristwatch for women.",
//     images: [],
//     price: 55.00,
//     categoryId: "Womens Watches",
//     video: "",
//   ),
//   Product(
//     id: "143",
//     title: "Gold Accent Watch",
//     description: "Stylish rose gold wristwatch for women.",
//     images: [],
//     price: 55.00,
//     categoryId: "Womens Watches",
//     video: "",
//   ),
// ];
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
// final List<Product> arabicProducts = [
//   // Beauty (1–3)
//   Product(
//     id: "0",
//     title: " كريم ترطيب للوجه كريم ترطيب للوجه",
//     description: "مرطب خفيف للاستخدام اليومي.",
//     images: [],
//     price: 12.99,
//     categoryId: "Beauty",
//     video: "",
//   ),
//   Product(
//     id: "1",
//     title: "سيروم فيتامين سي",
//     description: "سيروم لتفتيح البشرة ومنحها إشراقة.",
//     images: [],
//     price: 18.50,
//     categoryId: "Beauty",
//     video: "",
//   ),
//   Product(
//     id: "2",
//     title: "مجموعة فراشي مكياج",
//     description: "طقم مكون من 12 فرشاة مكياج عالية الجودة.",
//     images: [],
//     price: 22.00,
//     categoryId: "Beauty",
//     video: "",
//   ),
//   Product(
//     id: "900",
//     title: "كريم الليل التجديدي",
//     description: "طقم مكون من 12 فرشاة مكياج عالية الجودة.",
//     images: [],
//     price: 22.00,
//     categoryId: "Beauty",
//     video: "",
//   ),
//   Product(
//     id: "4",
//     title: "مقشر الوجه",
//     description: "طقم مكون من 12 فرشاة مكياج عالية الجودة.",
//     images: [],
//     price: 22.00,
//     categoryId: "Beauty",
//     video: "",
//   ),
//   Product(
//     id: "5",
//     title: "طقم بلسم الشفاه",
//     description: "طقم مكون من 12 فرشاة مكياج عالية الجودة.",
//     images: [],
//     price: 22.00,
//     categoryId: "Beauty",
//     video: "",
//   ),

//   // Fragrances (4–6)
//   Product(
//     id: "6",
//     title: "عطر نسيم البحر",
//     description: "رائحة منعشة مناسبة للاستخدام اليومي.",
//     images: [],
//     price: 35.00,
//     categoryId: "Fragrances",
//     video: "",
//   ),
//   Product(
//     id: "7",
//     title: "عطر أمبر وود عطر أمبر وود ",
//     description: "مزيج دافئ من الأخشاب والعنبر.",
//     images: [],
//     price: 49.99,
//     categoryId: "Fragrances",
//     video: "",
//   ),
//   Product(
//     id: "8",
//     title: "رذاذ زهري للجسم",
//     description: "معطر جسم برائحة زهرية لطيفة.",
//     images: [],
//     price: 14.99,
//     categoryId: "Fragrances",
//     video: "",
//   ),
//   Product(
//     id: "9",
//     title: "عطر الحمضيات",
//     description: "معطر جسم برائحة زهرية لطيفة.",
//     images: [],
//     price: 14.99,
//     categoryId: "Fragrances",
//     video: "",
//   ),
//   Product(
//     id: "10",
//     title: "عطر جوهر الورد",
//     description: "معطر جسم برائحة زهرية لطيفة.",
//     images: [],
//     price: 14.99,
//     categoryId: "Fragrances",
//     video: "",
//   ),
//   Product(
//     id: "11",
//     title: "رذاذ الفانيليا والتوابل",
//     description: "معطر جسم برائحة زهرية لطيفة.",
//     images: [],
//     price: 14.99,
//     categoryId: "Fragrances",
//     video: "",
//   ),

//   // Furniture (7–9)
//   Product(
//     id: "12",
//     title: "كنبة مودرن",
//     description: "كنبة ثلاثية بمظهر عصري وأرجل خشبية.",
//     images: [],
//     price: 450.00,
//     categoryId: "Furniture",
//     video: "",
//   ),
//   Product(
//     id: "13",
//     title: "طاولة قهوة خشبية",
//     description: "طاولة قهوة بسيطة من خشب البلوط.",
//     images: [],
//     price: 120.00,
//     categoryId: "Furniture",
//     video: "",
//   ),
//   Product(
//     id: "14",
//     title: "كرسي مكتب",
//     description: "كرسي مريح بارتفاع قابل للتعديل.",
//     images: [],
//     price: 99.99,
//     categoryId: "Furniture",
//     video: "",
//   ),
//   Product(
//     id: "15",
//     title: "وحدة رفوف للكتب",
//     description: "كرسي مريح بارتفاع قابل للتعديل.",
//     images: [],
//     price: 99.99,
//     categoryId: "Furniture",
//     video: "",
//   ),
//   Product(
//     id: "16",
//     title: "طقم طاولة طعام",
//     description: "كرسي مريح بارتفاع قابل للتعديل.",
//     images: [],
//     price: 99.99,
//     categoryId: "Furniture",
//     video: "",
//   ),
//   Product(
//     id: "17",
//     title: "خزانة تلفاز",
//     description: "كرسي مريح بارتفاع قابل للتعديل.",
//     images: [],
//     price: 99.99,
//     categoryId: "Furniture",
//     video: "",
//   ),

//   // Groceries (10–12)
//   Product(
//     id: "18",
//     title: "أرز بني عضوي",
//     description: "كيس 1 كجم من الأرز البني الصحي.",
//     images: [],
//     price: 5.99,
//     categoryId: "Groceries",
//     video: "",
//   ),
//   Product(
//     id: "19",
//     title: "زيت زيتون بكر ممتاز",
//     description: "زيت زيتون معصور على البارد بحجم 500 مل.",
//     images: [],
//     price: 8.99,
//     categoryId: "Groceries",
//     video: "",
//   ),
//   Product(
//     id: "20",
//     title: "حبوب قهوة عربية",
//     description: "حبوب قهوة محمصة عالية الجودة، 1 كجم.",
//     images: [],
//     price: 15.50,
//     categoryId: "Groceries",
//     video: "",
//   ),
//   Product(
//     id: "21",
//     title: "مكرونة من القمح الكامل",
//     description: "حبوب قهوة محمصة عالية الجودة، 1 كجم.",
//     images: [],
//     price: 15.50,
//     categoryId: "Groceries",
//     video: "",
//   ),
//   Product(
//     id: "22",
//     title: "عسل طبيعي",
//     description: "حبوب قهوة محمصة عالية الجودة، 1 كجم.",
//     images: [],
//     price: 15.50,
//     categoryId: "Groceries",
//     video: "",
//   ),
//   Product(
//     id: "23",
//     title: "لوز عضوي",
//     description: "حبوب قهوة محمصة عالية الجودة، 1 كجم.",
//     images: [],
//     price: 15.50,
//     categoryId: "Groceries",
//     video: "",
//   ),

//   // Home Decoration (13–15)
//   Product(
//     id: "24",
//     title: "لوحة فنية جدارية",
//     description: "لوحة بطابع مجرد عصري.",
//     images: [],
//     price: 40.00,
//     categoryId: "Home Decoration",
//     video: "",
//   ),
//   Product(
//     id: "25",
//     title: "فازة ديكور",
//     description: "فازة سيراميك بطبقة لامعة.",
//     images: [],
//     price: 25.00,
//     categoryId: "Home Decoration",
//     video: "",
//   ),
//   Product(
//     id: "26",
//     title: "سلسلة إضاءة LED",
//     description: "إضاءة خيطية دافئة للديكور.",
//     images: [],
//     price: 12.00,
//     categoryId: "Home Decoration",
//     video: "",
//   ),
//   Product(
//     id: "27",
//     title: "وعاء نبات داخلي",
//     description: "إضاءة خيطية دافئة للديكور.",
//     images: [],
//     price: 12.00,
//     categoryId: "Home Decoration",
//     video: "",
//   ),
//   Product(
//     id: "28",
//     title: "مرآة جدارية زخرفية",
//     description: "إضاءة خيطية دافئة للديكور.",
//     images: [],
//     price: 12.00,
//     categoryId: "Home Decoration",
//     video: "",
//   ),
//   Product(
//     id: "29",
//     title: "طقم شموع عطرية",
//     description: "إضاءة خيطية دافئة للديكور.",
//     images: [],
//     price: 12.00,
//     categoryId: "Home Decoration",
//     video: "",
//   ),

//   // Kitchen Accessories (16–18)
//   Product(
//     id: "30",
//     title: "طقم سكاكين مطبخ",
//     description: "طقم احترافي مكون من 5 سكاكين.",
//     images: [],
//     price: 32.00,
//     categoryId: "Kitchen Accessories",
//     video: "",
//   ),
//   Product(
//     id: "31",
//     title: "مقلاة غير لاصقة",
//     description: "مقلاة 28 سم بطبقة سيراميك.",
//     images: [],
//     price: 18.99,
//     categoryId: "Kitchen Accessories",
//     video: "",
//   ),
//   Product(
//     id: "32",
//     title: "علب زجاج للطعام",
//     description: "طقم مكون من 6 علب محكمة الإغلاق.",
//     images: [],
//     price: 20.00,
//     categoryId: "Kitchen Accessories",
//     video: "",
//   ),
//   Product(
//     id: "33",
//     title: "حصيرة خبز سيليكون",
//     description: "طقم مكون من 6 علب محكمة الإغلاق.",
//     images: [],
//     price: 20.00,
//     categoryId: "Kitchen Accessories",
//     video: "",
//   ),
//   Product(
//     id: "34",
//     title: "غلاية كهربائية",
//     description: "طقم مكون من 6 علب محكمة الإغلاق.",
//     images: [],
//     price: 20.00,
//     categoryId: "Kitchen Accessories",
//     video: "",
//   ),
//   Product(
//     id: "35",
//     title: "طقم أكواب قياس",
//     description: "طقم مكون من 6 علب محكمة الإغلاق.",
//     images: [],
//     price: 20.00,
//     categoryId: "Kitchen Accessories",
//     video: "",
//   ),

//   // Laptops (19–21)
//   Product(
//     id: "36",
//     title: "لابتوب ألترابوك برو 14",
//     description: "لابتوب نحيف مقاس 14 بوصة مع 16 جيجا رام.",
//     images: [],
//     price: 899.00,
//     categoryId: "Laptops",
//     video: "",
//   ),
//   Product(
//     id: "37",
//     title: "لابتوب الألعاب X",
//     description: "أداء عالي مع بطاقة RTX.",
//     images: [],
//     price: 1299.00,
//     categoryId: "Laptops",
//     video: "",
//   ),
//   Product(
//     id: "38",
//     title: "لابتوب خفيف الوزن لابتوب خفيف الوزن",
//     description: "مثالي للطلاب والعمل اليومي.",
//     images: [],
//     price: 550.00,
//     categoryId: "Laptops",
//     video: "",
//   ),
//   Product(
//     id: "39",
//     title: "لاب توب أعمال برو",
//     description: "مثالي للطلاب والعمل اليومي.",
//     images: [],
//     price: 550.00,
//     categoryId: "Laptops",
//     video: "",
//   ),
//   Product(
//     id: "40",
//     title: "لاب توب طالب 15",
//     description: "مثالي للطلاب والعمل اليومي.",
//     images: [],
//     price: 550.00,
//     categoryId: "Laptops",
//     video: "",
//   ),
//   Product(
//     id: "41",
//     title: "لاب توب 2 في 1 قابل للتحويل",
//     description: "مثالي للطلاب والعمل اليومي.",
//     images: [],
//     price: 550.00,
//     categoryId: "Laptops",
//     video: "",
//   ),

//   // Mens Shirts (22–24)
//   Product(
//     id: "42",
//     title: "قميص قطني رجالي",
//     description: "قميص قطن مناسب للاستخدام اليومي.",
//     images: [],
//     price: 19.99,
//     categoryId: "Mens Shirts",
//     video: "",
//   ),
//   Product(
//     id: "43",
//     title: "قميص رسمي أبيض",
//     description: "قميص كلاسيكي للمناسبات الرسمية.",
//     images: [],
//     price: 25.00,
//     categoryId: "Mens Shirts",
//     video: "",
//   ),
//   Product(
//     id: "44",
//     title: "قميص فلانيل",
//     description: "قميص شتوي بنقشة كاروهات.",
//     images: [],
//     price: 22.50,
//     categoryId: "Mens Shirts",
//     video: "",
//   ),
//   Product(
//     id: "45",
//     title: "قميص بولو مخطط",
//     description: "قميص شتوي بنقشة كاروهات.",
//     images: [],
//     price: 22.50,
//     categoryId: "Mens Shirts",
//     video: "",
//   ),
//   Product(
//     id: "46",
//     title: "قميص جينز بأزرار",
//     description: "قميص شتوي بنقشة كاروهات.",
//     images: [],
//     price: 22.50,
//     categoryId: "Mens Shirts",
//     video: "",
//   ),
//   Product(
//     id: "47",
//     title: "قميص صيفي كتان",
//     description: "قميص شتوي بنقشة كاروهات.",
//     images: [],
//     price: 22.50,
//     categoryId: "Mens Shirts",
//     video: "",
//   ),

//   // Mens Shoes (25–27)
//   Product(
//     id: "48",
//     title: "حذاء جري رجالي",
//     description: "حذاء رياضي خفيف ومريح.",
//     images: [],
//     price: 55.00,
//     categoryId: "Mens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "49",
//     title: "جزمة جلد رجالية",
//     description: "جزمة جلدية متينة باللون البني.",
//     images: [],
//     price: 89.00,
//     categoryId: "Mens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "50",
//     title: "حذاء لوفرز رجالي",
//     description: "حذاء مريح مناسب للاستخدام اليومي.",
//     images: [],
//     price: 45.00,
//     categoryId: "Mens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "51",
//     title: "حذاء رسمي",
//     description: "حذاء مريح مناسب للاستخدام اليومي.",
//     images: [],
//     price: 45.00,
//     categoryId: "Mens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "52",
//     title: "حذاء قماشي سهل الارتداء",
//     description: "حذاء مريح مناسب للاستخدام اليومي.",
//     images: [],
//     price: 45.00,
//     categoryId: "Mens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "53",
//     title: "حذاء عالي الكاحل رياضي",
//     description: "حذاء مريح مناسب للاستخدام اليومي.",
//     images: [],
//     price: 45.00,
//     categoryId: "Mens Shoes",
//     video: "",
//   ),

//   // Mens Watches (28–30)
//   Product(
//     id: "54",
//     title: "ساعة جلد كلاسيكية",
//     description: "ساعة أنالوج بحزام جلدي.",
//     images: [],
//     price: 60.00,
//     categoryId: "Mens Watches",
//     video: "",
//   ),
//   Product(
//     id: "55",
//     title: "ساعة معدنية رجالية",
//     description: "ساعة ستانلس ستيل مع عرض للتاريخ.",
//     images: [],
//     price: 75.00,
//     categoryId: "Mens Watches",
//     video: "",
//   ),
//   Product(
//     id: "56",
//     title: "ساعة رياضية رقمية",
//     description: "ساعة رقمية مقاومة للماء مع مؤقت.",
//     images: [],
//     price: 35.00,
//     categoryId: "Mens Watches",
//     video: "",
//   ),
//   Product(
//     id: "57",
//     title: "ساعة كرونوغراف",
//     description: "ساعة رقمية مقاومة للماء مع مؤقت.",
//     images: [],
//     price: 35.00,
//     categoryId: "Mens Watches",
//     video: "",
//   ),
//   Product(
//     id: "58",
//     title: "ساعة أنيقة رسمية",
//     description: "ساعة رقمية مقاومة للماء مع مؤقت.",
//     images: [],
//     price: 35.00,
//     categoryId: "Mens Watches",
//     video: "",
//   ),
//   Product(
//     id: "59",
//     title: "ساعة ذكية",
//     description: "ساعة رقمية مقاومة للماء مع مؤقت.",
//     images: [],
//     price: 35.00,
//     categoryId: "Mens Watches",
//     video: "",
//   ),

//   // Mobile Accessories (31–33)
//   Product(
//     id: "60",
//     title: "كابل شحن سريع",
//     description: "كابل USB-C بطول 1 متر.",
//     images: [],
//     price: 5.99,
//     categoryId: "Mobile Accessories",
//     video: "",
//   ),
//   Product(
//     id: "61",
//     title: "شاحن لاسلكي",
//     description: "لوحة شحن لاسلكية معتمدة.",
//     images: [],
//     price: 19.99,
//     categoryId: "Mobile Accessories",
//     video: "",
//   ),
//   Product(
//     id: "62",
//     title: "حامل موبايل ثلاثي",
//     description: "حامل هاتف صغير للتصوير.",
//     images: [],
//     price: 12.00,
//     categoryId: "Mobile Accessories",
//     video: "",
//   ),
//   Product(
//     id: "63",
//     title: "واقي شاشة زجاجي",
//     description: "حامل هاتف صغير للتصوير.",
//     images: [],
//     price: 12.00,
//     categoryId: "Mobile Accessories",
//     video: "",
//   ),
//   Product(
//     id: "64",
//     title: "غطاء هاتف سيليكون",
//     description: "حامل هاتف صغير للتصوير.",
//     images: [],
//     price: 12.00,
//     categoryId: "Mobile Accessories",
//     video: "",
//   ),
//   Product(
//     id: "65",
//     title: "حامل سيارة للهاتف",
//     description: "حامل هاتف صغير للتصوير.",
//     images: [],
//     price: 12.00,
//     categoryId: "Mobile Accessories",
//     video: "",
//   ),

//   // Motorcycle (34–36)
//   Product(
//     id: "66",
//     title: "خوذة موتوسيكل",
//     description: "خوذة حماية كاملة عالية الجودة.",
//     images: [],
//     price: 85.00,
//     categoryId: "Motorcycle",
//     video: "",
//   ),
//   Product(
//     id: "67",
//     title: "قفازات قيادة",
//     description: "قفازات حماية مناسبة للقيادة.",
//     images: [],
//     price: 20.00,
//     categoryId: "Motorcycle",
//     video: "",
//   ),
//   Product(
//     id: "68",
//     title: "حامل موبايل للدراجة",
//     description: "حامل قوي لتثبيت الهاتف على الدراجة.",
//     images: [],
//     price: 10.00,
//     categoryId: "Motorcycle",
//     video: "",
//   ),
//   Product(
//     id: "69",
//     title: "سترة واقية",
//     description: "حامل قوي لتثبيت الهاتف على الدراجة.",
//     images: [],
//     price: 10.00,
//     categoryId: "Motorcycle",
//     video: "",
//   ),
//   Product(
//     id: "70",
//     title: "أحذية ركوب الدراجة",
//     description: "حامل قوي لتثبيت الهاتف على الدراجة.",
//     images: [],
//     price: 10.00,
//     categoryId: "Motorcycle",
//     video: "",
//   ),
//   Product(
//     id: "71",
//     title: "أضواء إشارة للدراجة",
//     description: "حامل قوي لتثبيت الهاتف على الدراجة.",
//     images: [],
//     price: 10.00,
//     categoryId: "Motorcycle",
//     video: "",
//   ),

//   // Skin Care (37–39)
//   Product(
//     id: "72",
//     title: "جل ألوفيرا",
//     description: "جل مهدئ لترطيب البشرة.",
//     images: [],
//     price: 9.99,
//     categoryId: "Skin Care",
//     video: "",
//   ),
//   Product(
//     id: "73",
//     title: "واقي شمس SPF 50",
//     description: "حماية واسعة المدى من أشعة الشمس.",
//     images: [],
//     price: 14.50,
//     categoryId: "Skin Care",
//     video: "",
//   ),
//   Product(
//     id: "74",
//     title: "غسول وجه رغوي",
//     description: "غسول لطيف للاستخدام اليومي.",
//     images: [],
//     price: 7.99,
//     categoryId: "Skin Care",
//     video: "",
//   ),
//   Product(
//     id: "75",
//     title: "قناع الطين",
//     description: "غسول لطيف للاستخدام اليومي.",
//     images: [],
//     price: 7.99,
//     categoryId: "Skin Care",
//     video: "",
//   ),
//   Product(
//     id: "76",
//     title: "مرطب ليلي مغذي",
//     description: "غسول لطيف للاستخدام اليومي.",
//     images: [],
//     price: 7.99,
//     categoryId: "Skin Care",
//     video: "",
//   ),
//   Product(
//     id: "77",
//     title: "سيروم مضاد للتجاعيد",
//     description: "غسول لطيف للاستخدام اليومي.",
//     images: [],
//     price: 7.99,
//     categoryId: "Skin Care",
//     video: "",
//   ),

//   // Smartphones (40–42)
//   Product(
//     id: "78",
//     title: "هاتف X12",
//     description: "هاتف بشاشة 6.5 بوصة وبطارية قوية.",
//     images: [],
//     price: 450.00,
//     categoryId: "Smartphones",
//     video: "",
//   ),
//   Product(
//     id: "79",
//     title: "هاتف Nova A9",
//     description: "هاتف متوسط بقدرات تصوير ممتازة.",
//     images: [],
//     price: 320.00,
//     categoryId: "Smartphones",
//     video: "",
//   ),
//   Product(
//     id: "80",
//     title: "هاتف Mini Lite",
//     description: "هاتف صغير الحجم مع شحن سريع.",
//     images: [],
//     price: 219.00,
//     categoryId: "Smartphones",
//     video: "",
//   ),
//   Product(
//     id: "81",
//     title: "هاتف ألعاب 5G",
//     description: "هاتف صغير الحجم مع شحن سريع.",
//     images: [],
//     price: 219.00,
//     categoryId: "Smartphones",
//     video: "",
//   ),
//   Product(
//     id: "82",
//     title: "هاتف كاميرا احترافية",
//     description: "هاتف صغير الحجم مع شحن سريع.",
//     images: [],
//     price: 219.00,
//     categoryId: "Smartphones",
//     video: "",
//   ),
//   Product(
//     id: "83",
//     title: "هاتف اقتصادي",
//     description: "هاتف صغير الحجم مع شحن سريع.",
//     images: [],
//     price: 219.00,
//     categoryId: "Smartphones",
//     video: "",
//   ),

//   // Sports Accessories (43–45)
//   Product(
//     id: "84",
//     title: "مجموعة مطاطات رياضية",
//     description: "مجموعة من 5 مطاطات لتمارين القوة.",
//     images: [],
//     price: 15.00,
//     categoryId: "Sports Accessories",
//     video: "",
//   ),
//   Product(
//     id: "85",
//     title: "كرة قدم",
//     description: "كرة قدم بجودة المباريات.",
//     images: [],
//     price: 25.00,
//     categoryId: "Sports Accessories",
//     video: "",
//   ),
//   Product(
//     id: "86",
//     title: "حصيرة يوغا",
//     description: "حصيرة يوغا 6 مم غير قابلة للانزلاق.",
//     images: [],
//     price: 18.99,
//     categoryId: "Sports Accessories",
//     video: "",
//   ),
//   Product(
//     id: "87",
//     title: "قفازات ملاكمة",
//     description: "حصيرة يوغا 6 مم غير قابلة للانزلاق.",
//     images: [],
//     price: 18.99,
//     categoryId: "Sports Accessories",
//     video: "",
//   ),
//   Product(
//     id: "88",
//     title: "أوزان يد صغيرة",
//     description: "حصيرة يوغا 6 مم غير قابلة للانزلاق.",
//     images: [],
//     price: 18.99,
//     categoryId: "Sports Accessories",
//     video: "",
//   ),
//   Product(
//     id: "89",
//     title: "حبل قفز",
//     description: "حصيرة يوغا 6 مم غير قابلة للانزلاق.",
//     images: [],
//     price: 18.99,
//     categoryId: "Sports Accessories",
//     video: "",
//   ),

//   // Sunglasses (46–48)
//   Product(
//     id: "90",
//     title: "نظارة شمسية طيار",
//     description: "نظارة بإطار معدني كلاسيكي.",
//     images: [],
//     price: 30.00,
//     categoryId: "Sunglasses",
//     video: "",
//   ),
//   Product(
//     id: "91",
//     title: "نظارة قيادة مضادة للوهج",
//     description: "عدسات مستقطبة لتقليل الانعكاس.",
//     images: [],
//     price: 22.00,
//     categoryId: "Sunglasses",
//     video: "",
//   ),
//   Product(
//     id: "92",
//     title: "نظارة رياضية",
//     description: "نظارة خفيفة مخصصة للرياضة.",
//     images: [],
//     price: 18.00,
//     categoryId: "Sunglasses",
//     video: "",
//   ),
//   Product(
//     id: "93",
//     title: "نظارات شمسية عصرية",
//     description: "نظارة خفيفة مخصصة للرياضة.",
//     images: [],
//     price: 18.00,
//     categoryId: "Sunglasses",
//     video: "",
//   ),
//   Product(
//     id: "94",
//     title: "نظارات إطار بلاستيكي",
//     description: "نظارة خفيفة مخصصة للرياضة.",
//     images: [],
//     price: 18.00,
//     categoryId: "Sunglasses",
//     video: "",
//   ),
//   Product(
//     id: "95",
//     title: "نظارات مقاومة الأشعة",
//     description: "نظارة خفيفة مخصصة للرياضة.",
//     images: [],
//     price: 18.00,
//     categoryId: "Sunglasses",
//     video: "",
//   ),

//   // Tablets (49–51)
//   Product(
//     id: "96",
//     title: "جهاز لوحي Pro 10",
//     description: "جهاز لوحي مقاس 10 بوصة للعمل والإنتاجية.",
//     images: [],
//     price: 499.00,
//     categoryId: "Tablets",
//     video: "",
//   ),
//   Product(
//     id: "97",
//     title: "تابلت تعليمي للأطفال",
//     description: "تابلت قوي ومتين مخصص للأطفال.",
//     images: [],
//     price: 150.00,
//     categoryId: "Tablets",
//     video: "",
//   ),
//   Product(
//     id: "98",
//     title: "تابلت ميديا صغير",
//     description: "تابلت مقاس 8 بوصة للترفيه.",
//     images: [],
//     price: 179.00,
//     categoryId: "Tablets",
//     video: "",
//   ),
//   Product(
//     id: "99",
//     title: "تابلت ألعاب",
//     description: "تابلت مقاس 8 بوصة للترفيه.",
//     images: [],
//     price: 179.00,
//     categoryId: "Tablets",
//     video: "",
//   ),
//   Product(
//     id: "100",
//     title: "تابلت للرسم الرقمي",
//     description: "تابلت مقاس 8 بوصة للترفيه.",
//     images: [],
//     price: 179.00,
//     categoryId: "Tablets",
//     video: "",
//   ),
//   Product(
//     id: "101",
//     title: "تابلت مكتبي",
//     description: "تابلت مقاس 8 بوصة للترفيه.",
//     images: [],
//     price: 179.00,
//     categoryId: "Tablets",
//     video: "",
//   ),

//   // Tops (52–54)
//   Product(
//     id: "102",
//     title: "توب قطن نسائي",
//     description: "توب ناعم ومريح للاستخدام اليومي.",
//     images: [],
//     price: 12.00,
//     categoryId: "Tops",
//     video: "",
//   ),
//   Product(
//     id: "103",
//     title: "توب كت صيفي",
//     description: "توب خفيف مناسب لفصل الصيف.",
//     images: [],
//     price: 8.99,
//     categoryId: "Tops",
//     video: "",
//   ),
//   Product(
//     id: "104",
//     title: "بلوزة كم طويل",
//     description: "بلوزة أنيقة مناسبة للخروج.",
//     images: [],
//     price: 18.00,
//     categoryId: "Tops",
//     video: "",
//   ),
//   Product(
//     id: "105",
//     title: "توب حريري رسمي",
//     description: "بلوزة أنيقة مناسبة للخروج.",
//     images: [],
//     price: 18.00,
//     categoryId: "Tops",
//     video: "",
//   ),
//   Product(
//     id: "106",
//     title: "توب رياضي",
//     description: "بلوزة أنيقة مناسبة للخروج.",
//     images: [],
//     price: 18.00,
//     categoryId: "Tops",
//     video: "",
//   ),
//   Product(
//     id: "107",
//     title: "توب صيفي مزخرف",
//     description: "بلوزة أنيقة مناسبة للخروج.",
//     images: [],
//     price: 18.00,
//     categoryId: "Tops",
//     video: "",
//   ),

//   // Vehicle (55–57)
//   Product(
//     id: "108",
//     title: "مكنسة سيارات",
//     description: "مكنسة كهربائية محمولة للسيارة.",
//     images: [],
//     price: 25.00,
//     categoryId: "Vehicle",
//     video: "",
//   ),
//   Product(
//     id: "109",
//     title: "معطر تابلوه للسيارة",
//     description: "معطر جل برائحة تدوم طويلاً.",
//     images: [],
//     price: 6.50,
//     categoryId: "Vehicle",
//     video: "",
//   ),
//   Product(
//     id: "110",
//     title: "حامل هاتف للسيارة",
//     description: "حامل دوّار لتثبيت الهاتف على التابلوه.",
//     images: [],
//     price: 9.99,
//     categoryId: "Vehicle",
//     video: "",
//   ),
//   Product(
//     id: "111",
//     title: "مظلة سيارة",
//     description: "حامل دوّار لتثبيت الهاتف على التابلوه.",
//     images: [],
//     price: 9.99,
//     categoryId: "Vehicle",
//     video: "",
//   ),
//   Product(
//     id: "112",
//     title: "وسادة دعم للسيارة",
//     description: "حامل دوّار لتثبيت الهاتف على التابلوه.",
//     images: [],
//     price: 9.99,
//     categoryId: "Vehicle",
//     video: "",
//   ),
//   Product(
//     id: "113",
//     title: "غطاء مقعد السيارة",
//     description: "حامل دوّار لتثبيت الهاتف على التابلوه.",
//     images: [],
//     price: 9.99,
//     categoryId: "Vehicle",
//     video: "",
//   ),

//   // Womens Bags (58–60)
//   Product(
//     id: "114",
//     title: "شنطة يد جلد",
//     description: "شنطة يد أنيقة من الجلد الطبيعي.",
//     images: [],
//     price: 65.00,
//     categoryId: "Womens Bags",
//     video: "",
//   ),
//   Product(
//     id: "115",
//     title: "شنطة كروس",
//     description: "شنطة خفيفة بتصميم مريح.",
//     images: [],
//     price: 32.00,
//     categoryId: "Womens Bags",
//     video: "",
//   ),
//   Product(
//     id: "116",
//     title: "شنطة سفر كبيرة",
//     description: "شنطة واسعة ومتينة للسفر.",
//     images: [],
//     price: 40.00,
//     categoryId: "Womens Bags",
//     video: "",
//   ),
//   Product(
//     id: "117",
//     title: "حقيبة صغيرة مسائية",
//     description: "شنطة واسعة ومتينة للسفر.",
//     images: [],
//     price: 40.00,
//     categoryId: "Womens Bags",
//     video: "",
//   ),
//   Product(
//     id: "118",
//     title: "حقيبة ظهر أنيقة",
//     description: "شنطة واسعة ومتينة للسفر.",
//     images: [],
//     price: 40.00,
//     categoryId: "Womens Bags",
//     video: "",
//   ),
//   Product(
//     id: "119",
//     title: "حقيبة شاطئية",
//     description: "شنطة واسعة ومتينة للسفر.",
//     images: [],
//     price: 40.00,
//     categoryId: "Womens Bags",
//     video: "",
//   ),

//   // Womens Dresses (61–63)
//   Product(
//     id: "120",
//     title: "فستان صيفي مزهر",
//     description: "فستان خفيف ومريح مناسب للصيف.",
//     images: [],
//     price: 28.00,
//     categoryId: "IWomens Dresses",
//     video: "",
//   ),
//   Product(
//     id: "121",
//     title: "فستان سهرة",
//     description: "فستان أنيق للمناسبات الخاصة.",
//     images: [],
//     price: 75.00,
//     categoryId: "IWomens Dresses",
//     video: "",
//   ),
//   Product(
//     id: "122",
//     title: "فستان ميدي كاجوال",
//     description: "فستان مريح بطول متوسط.",
//     images: [],
//     price: 30.00,
//     categoryId: "IWomens Dresses",
//     video: "",
//   ),
//   Product(
//     id: "123",
//     title: "فستان مكتب رسمي",
//     description: "فستان مريح بطول متوسط.",
//     images: [],
//     price: 30.00,
//     categoryId: "IWomens Dresses",
//     video: "",
//   ),
//   Product(
//     id: "124",
//     title: "فستان سهرة قصير",
//     description: "فستان مريح بطول متوسط.",
//     images: [],
//     price: 30.00,
//     categoryId: "IWomens Dresses",
//     video: "",
//   ),
//   Product(
//     id: "125",
//     title: "فستان كاجوال فضفاض",
//     description: "فستان مريح بطول متوسط.",
//     images: [],
//     price: 30.00,
//     categoryId: "IWomens Dresses",
//     video: "",
//   ),

//   // Womens Jewellery (64–66)
//   Product(
//     id: "126",
//     title: "عقد مطلي بالذهب",
//     description: "عقد أنيق مطلي بالذهب.",
//     images: [],
//     price: 20.00,
//     categoryId: "Womens Jewellery",
//     video: "",
//   ),
//   Product(
//     id: "127",
//     title: "إسوارة فضية",
//     description: "إسوارة فضية أنيقة.",
//     images: [],
//     price: 18.00,
//     categoryId: "Womens Jewellery",
//     video: "",
//   ),
//   Product(
//     id: "128",
//     title: "حلق ماس صغير",
//     description: "أقراط ماس كلاسيكية.",
//     images: [],
//     price: 49.00,
//     categoryId: "Womens Jewellery",
//     video: "",
//   ),
//   Product(
//     id: "129",
//     title: "خاتم فضي",
//     description: "أقراط ماس كلاسيكية.",
//     images: [],
//     price: 49.00,
//     categoryId: "Womens Jewellery",
//     video: "",
//   ),
//   Product(
//     id: "130",
//     title: "أساور متعددة الطبقات",
//     description: "أقراط ماس كلاسيكية.",
//     images: [],
//     price: 49.00,
//     categoryId: "Womens Jewellery",
//     video: "",
//   ),
//   Product(
//     id: "131",
//     title: "سلسلة ذهبية بسيطة",
//     description: "أقراط ماس كلاسيكية.",
//     images: [],
//     price: 49.00,
//     categoryId: "Womens Jewellery",
//     video: "",
//   ),

//   // Womens Shoes (67–69)
//   Product(
//     id: "132",
//     title: "كعب عالي نسائي",
//     description: "حذاء بكعب عالي للمناسبات.",
//     images: [],
//     price: 35.00,
//     categoryId: "Womens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "133",
//     title: "حذاء جري نسائي",
//     description: "حذاء مريح للتمارين والجري.",
//     images: [],
//     price: 50.00,
//     categoryId: "Womens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "134",
//     title: "حذاء فلات نسائي",
//     description: "حذاء خفيف للاستخدام اليومي.",
//     images: [],
//     price: 22.00,
//     categoryId: "Womens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "135",
//     title: "صندل صيفي",
//     description: "حذاء خفيف للاستخدام اليومي.",
//     images: [],
//     price: 22.00,
//     categoryId: "Womens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "136",
//     title: "حذاء رسمي نسائي",
//     description: "حذاء خفيف للاستخدام اليومي.",
//     images: [],
//     price: 22.00,
//     categoryId: "Womens Shoes",
//     video: "",
//   ),
//   Product(
//     id: "137",
//     title: "حذاء بوت أنيق",
//     description: "حذاء خفيف للاستخدام اليومي.",
//     images: [],
//     price: 22.00,
//     categoryId: "Womens Shoes",
//     video: "",
//   ),

//   // Womens Watches (70)
//   Product(
//     id: "138",
//     title: "ساعة روز جولد نسائية",
//     description: "ساعة نسائية أنيقة بلون روز جولد.",
//     images: [],
//     price: 55.00,
//     categoryId: "Womens Watches",
//     video: "",
//   ),
//   Product(
//     id: "139",
//     title: "ساعة ذكية للنساء",
//     description: "ساعة نسائية أنيقة بلون روز جولد.",
//     images: [],
//     price: 55.00,
//     categoryId: "Womens Watches",
//     video: "",
//   ),
//   Product(
//     id: "140",
//     title: "ساعة فاخرة مرصعة",
//     description: "ساعة نسائية أنيقة بلون روز جولد.",
//     images: [],
//     price: 55.00,
//     categoryId: "Womens Watches",
//     video: "",
//   ),
//   Product(
//     id: "141",
//     title: "ساعة عملية يومية",
//     description: "ساعة نسائية أنيقة بلون روز جولد.",
//     images: [],
//     price: 55.00,
//     categoryId: "Womens Watches",
//     video: "",
//   ),
//   Product(
//     id: "142",
//     title: "ساعة ذهبية وردية",
//     description: "ساعة نسائية أنيقة بلون روز جولد.",
//     images: [],
//     price: 55.00,
//     categoryId: "Womens Watches",
//     video: "",
//   ),
//   Product(
//     id: "143",
//     title: "ساعة رياضية نسائية",
//     description: "ساعة نسائية أنيقة بلون روز جولد.",
//     images: [],
//     price: 55.00,
//     categoryId: "Womens Watches",
//     video: "",
//   ),
// ];
