class Product {
  final String id;
  final String title;
  final String description;
  final double price;
  final bool favorite;
  final List<String> images;
  final String? video;
  final String categoryId;

  Product({
    required this.id,
    required this.title,
    required this.description,
    required this.images,
    required this.favorite,
    required this.price,
    required this.categoryId,
    this.video,
  });
}

final List<Product> englishProducts = [
  // Beauty (1–3)
  Product(
    id: "1",
    title: "Hydrating Face Cream",
    description: "A lightweight moisturizer for daily hydration.",
    images: [],
    favorite: false,
    price: 12.99,
    categoryId: "Beauty",
    video: "",
  ),
  Product(
    id: "2",
    title: "Vitamin C Serum",
    description: "Brightening serum for glowing skin.",
    images: [],
    favorite: false,
    price: 18.50,
    categoryId: "Beauty",
    video: "",
  ),
  Product(
    id: "3",
    title: "Makeup Brush Set",
    description: "Premium-quality 12-piece makeup brush set.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Beauty",
    video: "",
  ),
  Product(
    id: "4",
    title: "Night Repair Cream",
    description: "Premium-quality 12-piece makeup brush set.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Beauty",
    video: "",
  ),
  Product(
    id: "5",
    title: "Exfoliating Scrub",
    description: "Premium-quality 12-piece makeup brush set.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Beauty",
    video: "",
  ),
  Product(
    id: "6",
    title: "Lip Balm Set",
    description: "Premium-quality 12-piece makeup brush set.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Beauty",
    video: "",
  ),

  // Fragrances (4–6)
  Product(
    id: "7",
    title: "Ocean Breeze Perfume",
    description: "Fresh aquatic fragrance for daily wear.",
    images: [],
    favorite: false,
    price: 35.00,
    categoryId: "Fragrances",
    video: "",
  ),
  Product(
    id: "8",
    title: "Amber Wood Eau de Parfum",
    description: "Warm woody scent with amber undertones.",
    images: [],
    favorite: false,
    price: 49.99,
    categoryId: "Fragrances",
    video: "",
  ),
  Product(
    id: "9",
    title: "Floral Mist Spray",
    description: "Light floral body mist with long-lasting freshness.",
    images: [],
    favorite: false,
    price: 14.99,
    categoryId: "Fragrances",
    video: "",
  ),
  Product(
    id: "10",
    title: "Citrus Splash Eau de Toilette",
    description: "Light floral body mist with long-lasting freshness.",
    images: [],
    favorite: false,
    price: 14.99,
    categoryId: "Fragrances",
    video: "",
  ),
  Product(
    id: "11",
    title: "Rose Essence Perfume",
    description: "Light floral body mist with long-lasting freshness.",
    images: [],
    favorite: false,
    price: 14.99,
    categoryId: "Fragrances",
    video: "",
  ),
  Product(
    id: "12",
    title: "Vanilla Spice Body Mist",
    description: "Light floral body mist with long-lasting freshness.",
    images: [],
    favorite: false,
    price: 14.99,
    categoryId: "Fragrances",
    video: "",
  ),

  // Furniture (7–9)
  Product(
    id: "13",
    title: "Modern Sofa",
    description: "Three-seater fabric sofa with wooden legs.",
    images: [],
    favorite: false,
    price: 450.00,
    categoryId: "Furniture",
    video: "",
  ),
  Product(
    id: "1400",
    title: "Wooden Coffee Table",
    description: "Minimalist coffee table made of oak wood.",
    images: [],
    favorite: false,
    price: 120.00,
    categoryId: "Furniture",
    video: "",
  ),
  Product(
    id: "14",
    title: "Office Chair",
    description: "Ergonomic chair with adjustable height and back support.",
    images: [],
    favorite: false,
    price: 99.99,
    categoryId: "Furniture",
    video: "",
  ),
  Product(
    id: "15",
    title: "Bookshelf Unit",
    description: "Ergonomic chair with adjustable height and back support.",
    images: [],
    favorite: false,
    price: 99.99,
    categoryId: "Furniture",
    video: "",
  ),
  Product(
    id: "16",
    title: "Dining Table Set",
    description: "Ergonomic chair with adjustable height and back support.",
    images: [],
    favorite: false,
    price: 99.99,
    categoryId: "Furniture",
    video: "",
  ),
  Product(
    id: "17",
    title: "TV Stand Cabinet",
    description: "Ergonomic chair with adjustable height and back support.",
    images: [],
    favorite: false,
    price: 99.99,
    categoryId: "Furniture",
    video: "",
  ),

  // Groceries (10–12)
  Product(
    id: "18",
    title: "Organic Brown Rice",
    description: "1kg pack of healthy organic brown rice.",
    images: [],
    favorite: false,
    price: 5.99,
    categoryId: "Groceries",
    video: "",
  ),
  Product(
    id: "19",
    title: "Extra Virgin Olive Oil",
    description: "Cold-pressed olive oil, 500ml bottle.",
    images: [],
    favorite: false,
    price: 8.99,
    categoryId: "Groceries",
    video: "",
  ),
  Product(
    id: "20",
    title: "Arabian Coffee Beans",
    description: "Premium roasted coffee beans, 1kg.",
    images: [],
    favorite: false,
    price: 15.50,
    categoryId: "Groceries",
    video: "",
  ),
  Product(
    id: "21",
    title: "Whole Wheat Pasta",
    description: "Premium roasted coffee beans, 1kg.",
    images: [],
    favorite: false,
    price: 15.50,
    categoryId: "Groceries",
    video: "",
  ),
  Product(
    id: "22",
    title: "Honey Jar",
    description: "Premium roasted coffee beans, 1kg.",
    images: [],
    favorite: false,
    price: 15.50,
    categoryId: "Groceries",
    video: "",
  ),
  Product(
    id: "23",
    title: "Organic Almonds",
    description: "Premium roasted coffee beans, 1kg.",
    images: [],
    favorite: false,
    price: 15.50,
    categoryId: "Groceries",
    video: "",
  ),

  // Home Decoration (13–15)
  Product(
    id: "24",
    title: "Wall Art Canvas",
    description: "Minimalist modern abstract painting.",
    images: [],
    favorite: false,
    price: 40.00,
    categoryId: "Home Decoration",
    video: "",
  ),
  Product(
    id: "25",
    title: "Decorative Vase",
    description: "Ceramic vase with glossy finish.",
    images: [],
    favorite: false,
    price: 25.00,
    categoryId: "Home Decoration",
    video: "",
  ),
  Product(
    id: "26",
    title: "LED String Lights",
    description: "Warm white decorative string lights.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Home Decoration",
    video: "",
  ),
  Product(
    id: "27",
    title: "Indoor Plant Pot",
    description: "Warm white decorative string lights.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Home Decoration",
    video: "",
  ),
  Product(
    id: "28",
    title: "Decorative Wall Mirror",
    description: "Warm white decorative string lights.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Home Decoration",
    video: "",
  ),
  Product(
    id: "29",
    title: "Scented Candles Set",
    description: "Warm white decorative string lights.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Home Decoration",
    video: "",
  ),

  // Kitchen Accessories (16–18)
  Product(
    id: "30",
    title: "Stainless Steel Knife Set",
    description: "5-piece premium kitchen knife set.",
    images: [],
    favorite: false,
    price: 32.00,
    categoryId: "Kitchen Accessories",
    video: "",
  ),
  Product(
    id: "31",
    title: "Non-stick Frying Pan",
    description: "Durable 28cm frying pan with ceramic coating.",
    images: [],
    favorite: false,
    price: 18.99,
    categoryId: "Kitchen Accessories",
    video: "",
  ),
  Product(
    id: "32",
    title: "Glass Food Containers",
    description: "Set of 6 airtight food storage containers.",
    images: [],
    favorite: false,
    price: 20.00,
    categoryId: "Kitchen Accessories",
    video: "",
  ),
  Product(
    id: "33",
    title: "Silicone Baking Mat",
    description: "Set of 6 airtight food storage containers.",
    images: [],
    favorite: false,
    price: 20.00,
    categoryId: "Kitchen Accessories",
    video: "",
  ),
  Product(
    id: "34",
    title: "Electric Kettle",
    description: "Set of 6 airtight food storage containers.",
    images: [],
    favorite: false,
    price: 20.00,
    categoryId: "Kitchen Accessories",
    video: "",
  ),
  Product(
    id: "35",
    title: "Measuring Cups Set",
    description: "Set of 6 airtight food storage containers.",
    images: [],
    favorite: false,
    price: 20.00,
    categoryId: "Kitchen Accessories",
    video: "",
  ),

  // Laptops (19–21)
  Product(
    id: "36",
    title: "Ultrabook Pro 14",
    description: "Slim 14-inch laptop with 16GB RAM.",
    images: [],
    favorite: false,
    price: 899.00,
    categoryId: "Laptops",
    video: "",
  ),
  Product(
    id: "37",
    title: "Gaming Laptop X",
    description: "High-performance laptop with RTX graphics.",
    images: [],
    favorite: false,
    price: 1299.00,
    categoryId: "Laptops",
    video: "",
  ),
  Product(
    id: "38",
    title: "Lightweight Notebook",
    description: "Portable notebook ideal for students.",
    images: [],
    favorite: false,
    price: 550.00,
    categoryId: "Laptops",
    video: "",
  ),
  Product(
    id: "39",
    title: "Business Laptop Pro",
    description: "Portable notebook ideal for students.",
    images: [],
    favorite: false,
    price: 550.00,
    categoryId: "Laptops",
    video: "",
  ),
  Product(
    id: "40",
    title: "Student Laptop 15",
    description: "Portable notebook ideal for students.",
    images: [],
    favorite: false,
    price: 550.00,
    categoryId: "Laptops",
    video: "",
  ),
  Product(
    id: "41",
    title: "Convertible 2-in-1 Laptop",
    description: "Portable notebook ideal for students.",
    images: [],
    favorite: false,
    price: 550.00,
    categoryId: "Laptops",
    video: "",
  ),

  // Mens Shirts (22–24)
  Product(
    id: "42",
    title: "Casual Cotton Shirt",
    description: "Slim-fit cotton shirt for daily wear.",
    images: [],
    favorite: false,
    price: 19.99,
    categoryId: "Mens Shirts",
    video: "",
  ),
  Product(
    id: "43",
    title: "Formal White Shirt",
    description: "Classic white shirt for formal occasions.",
    images: [],
    favorite: false,
    price: 25.00,
    categoryId: "Mens Shirts",
    video: "",
  ),
  Product(
    id: "44",
    title: "Plaid Flannel Shirt",
    description: "Warm flannel shirt with plaid design.",
    images: [],
    favorite: false,
    price: 22.50,
    categoryId: "Mens Shirts",
    video: "",
  ),
  Product(
    id: "45",
    title: "Striped Polo Shirt",
    description: "Warm flannel shirt with plaid design.",
    images: [],
    favorite: false,
    price: 22.50,
    categoryId: "Mens Shirts",
    video: "",
  ),
  Product(
    id: "46",
    title: "Denim Button Shirt",
    description: "Warm flannel shirt with plaid design.",
    images: [],
    favorite: false,
    price: 22.50,
    categoryId: "Mens Shirts",
    video: "",
  ),
  Product(
    id: "47",
    title: "Linen Summer Shirt",
    description: "Warm flannel shirt with plaid design.",
    images: [],
    favorite: false,
    price: 22.50,
    categoryId: "Mens Shirts",
    video: "",
  ),

  // Mens Shoes (25–27)
  Product(
    id: "48",
    title: "Running Sneakers",
    description: "Breathable sports sneakers for men.",
    images: [],
    favorite: false,
    price: 55.00,
    categoryId: "Mens Shoes",
    video: "",
  ),
  Product(
    id: "49",
    title: "Leather Boots",
    description: "Durable brown leather boots.",
    images: [],
    favorite: false,
    price: 89.00,
    categoryId: "Mens Shoes",
    video: "",
  ),
  Product(
    id: "50",
    title: "Casual Loafers",
    description: "Comfortable loafers suitable for daily wear.",
    images: [],
    favorite: false,
    price: 45.00,
    categoryId: "Mens Shoes",
    video: "",
  ),
  Product(
    id: "51",
    title: "Formal Dress Shoes",
    description: "Comfortable loafers suitable for daily wear.",
    images: [],
    favorite: false,
    price: 45.00,
    categoryId: "Mens Shoes",
    video: "",
  ),
  Product(
    id: "52",
    title: "Canvas Slip-Ons",
    description: "Comfortable loafers suitable for daily wear.",
    images: [],
    favorite: false,
    price: 45.00,
    categoryId: "Mens Shoes",
    video: "",
  ),
  Product(
    id: "53",
    title: "High-Top Trainers",
    description: "Comfortable loafers suitable for daily wear.",
    images: [],
    favorite: false,
    price: 45.00,
    categoryId: "Mens Shoes",
    video: "",
  ),

  // Mens Watches (28–30)
  Product(
    id: "54",
    title: "Analog Leather Watch",
    description: "Classic analog watch with leather strap.",
    images: [],
    favorite: false,
    price: 60.00,
    categoryId: "Mens Watches",
    video: "",
  ),
  Product(
    id: "55",
    title: "Steel Wrist Watch",
    description: "Stainless steel men’s watch with date feature.",
    images: [],
    favorite: false,
    price: 75.00,
    categoryId: "Mens Watches",
    video: "",
  ),
  Product(
    id: "56",
    title: "Digital Sports Watch",
    description: "Waterproof digital watch with stopwatch.",
    images: [],
    favorite: false,
    price: 35.00,
    categoryId: "Mens Watches",
    video: "",
  ),
  Product(
    id: "57",
    title: "Chronograph Watch",
    description: "Waterproof digital watch with stopwatch.",
    images: [],
    favorite: false,
    price: 35.00,
    categoryId: "Mens Watches",
    video: "",
  ),
  Product(
    id: "58",
    title: "Minimalist Black Watch",
    description: "Waterproof digital watch with stopwatch.",
    images: [],
    favorite: false,
    price: 35.00,
    categoryId: "Mens Watches",
    video: "",
  ),
  Product(
    id: "59",
    title: "Silver Dress Watch",
    description: "Waterproof digital watch with stopwatch.",
    images: [],
    favorite: false,
    price: 35.00,
    categoryId: "Mens Watches",
    video: "",
  ),

  // Mobile Accessories (31–33)
  Product(
    id: "60",
    title: "Fast Charging Cable",
    description: "USB-C fast charging cable, 1m.",
    images: [],
    favorite: false,
    price: 5.99,
    categoryId: "Mobile Accessories",
    video: "",
  ),
  Product(
    id: "61",
    title: "Wireless Charger",
    description: "Qi-certified wireless charging pad.",
    images: [],
    favorite: false,
    price: 19.99,
    categoryId: "Mobile Accessories",
    video: "",
  ),
  Product(
    id: "62",
    title: "Phone Tripod",
    description: "Compact tripod for smartphones.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Mobile Accessories",
    video: "",
  ),
  Product(
    id: "63",
    title: "Screen Protector Pack",
    description: "Compact tripod for smartphones.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Mobile Accessories",
    video: "",
  ),
  Product(
    id: "64",
    title: "Phone Case",
    description: "Compact tripod for smartphones.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Mobile Accessories",
    video: "",
  ),
  Product(
    id: "65",
    title: "Car Charger Adapter",
    description: "Compact tripod for smartphones.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Mobile Accessories",
    video: "",
  ),

  // Motorcycle (34–36)
  Product(
    id: "66",
    title: "Motorcycle Helmet",
    description: "High-quality full-face helmet.",
    images: [],
    favorite: false,
    price: 85.00,
    categoryId: "Motorcycle",
    video: "",
  ),
  Product(
    id: "67",
    title: "Riding Gloves",
    description: "Protective gloves for bikers.",
    images: [],
    favorite: false,
    price: 20.00,
    categoryId: "Motorcycle",
    video: "",
  ),
  Product(
    id: "68",
    title: "Bike Phone Holder",
    description: "Durable mobile phone mount for bikes.",
    images: [],
    favorite: false,
    price: 10.00,
    categoryId: "Motorcycle",
    video: "",
  ),
  Product(
    id: "69",
    title: "Reflective Safety Vest",
    description: "Durable mobile phone mount for bikes.",
    images: [],
    favorite: false,
    price: 10.00,
    categoryId: "Motorcycle",
    video: "",
  ),
  Product(
    id: "70",
    title: "Motorbike Cover",
    description: "Durable mobile phone mount for bikes.",
    images: [],
    favorite: false,
    price: 10.00,
    categoryId: "Motorcycle",
    video: "",
  ),
  Product(
    id: "71",
    title: "LED Bike Lights",
    description: "Durable mobile phone mount for bikes.",
    images: [],
    favorite: false,
    price: 10.00,
    categoryId: "Motorcycle",
    video: "",
  ),

  // Skin Care (37–39)
  Product(
    id: "72",
    title: "Aloe Vera Gel",
    description: "Soothing gel for skin hydration.",
    images: [],
    favorite: false,
    price: 9.99,
    categoryId: "Skin Care",
    video: "",
  ),
  Product(
    id: "73",
    title: "Sunscreen SPF 50",
    description: "Broad-spectrum sun protection.",
    images: [],
    favorite: false,
    price: 14.50,
    categoryId: "Skin Care",
    video: "",
  ),
  Product(
    id: "74",
    title: "Foaming Face Wash",
    description: "Gentle cleanser for daily use.",
    images: [],
    favorite: false,
    price: 7.99,
    categoryId: "Skin Care",
    video: "",
  ),
  Product(
    id: "75",
    title: "Charcoal Face Mask",
    description: "Gentle cleanser for daily use.",
    images: [],
    favorite: false,
    price: 7.99,
    categoryId: "Skin Care",
    video: "",
  ),
  Product(
    id: "76",
    title: "Hydrating Toner",
    description: "Gentle cleanser for daily use.",
    images: [],
    favorite: false,
    price: 7.99,
    categoryId: "Skin Care",
    video: "",
  ),
  Product(
    id: "77",
    title: "Anti-Aging Cream",
    description: "Gentle cleanser for daily use.",
    images: [],
    favorite: false,
    price: 7.99,
    categoryId: "Skin Care",
    video: "",
  ),

  // Smartphones (40–42)
  Product(
    id: "78",
    title: "Smartphone X12",
    description: "6.5-inch smartphone with great battery life.",
    images: [],
    favorite: false,
    price: 450.00,
    categoryId: "Smartphones",
    video: "",
  ),
  Product(
    id: "79",
    title: "Smartphone Nova A9",
    description: "Mid-range phone with excellent camera.",
    images: [],
    favorite: false,
    price: 320.00,
    categoryId: "Smartphones",
    video: "",
  ),
  Product(
    id: "80",
    title: "Smartphone Mini Lite",
    description: "Compact smartphone with fast charging.",
    images: [],
    favorite: false,
    price: 219.00,
    categoryId: "Smartphones",
    video: "",
  ),
  Product(
    id: "81",
    title: "Smartphone Pro Max",
    description: "Compact smartphone with fast charging.",
    images: [],
    favorite: false,
    price: 219.00,
    categoryId: "Smartphones",
    video: "",
  ),
  Product(
    id: "82",
    title: "Budget Smartphone Z5",
    description: "Compact smartphone with fast charging.",
    images: [],
    favorite: false,
    price: 219.00,
    categoryId: "Smartphones",
    video: "",
  ),
  Product(
    id: "83",
    title: "Foldable Smartphone F1",
    description: "Compact smartphone with fast charging.",
    images: [],
    favorite: false,
    price: 219.00,
    categoryId: "Smartphones",
    video: "",
  ),

  // Sports Accessories (43–45)
  Product(
    id: "84",
    title: "Fitness Resistance Bands",
    description: "Set of 5 resistance bands for workouts.",
    images: [],
    favorite: false,
    price: 15.00,
    categoryId: "Sports Accessories",
    video: "",
  ),
  Product(
    id: "85",
    title: "Football",
    description: "Professional match-quality football.",
    images: [],
    favorite: false,
    price: 25.00,
    categoryId: "Sports Accessories",
    video: "",
  ),
  Product(
    id: "86",
    title: "Yoga Mat",
    description: "Non-slip 6mm yoga mat.",
    images: [],
    favorite: false,
    price: 18.99,
    categoryId: "Sports Accessories",
    video: "",
  ),
  Product(
    id: "87",
    title: "Dumbbell Set",
    description: "Non-slip 6mm yoga mat.",
    images: [],
    favorite: false,
    price: 18.99,
    categoryId: "Sports Accessories",
    video: "",
  ),
  Product(
    id: "88",
    title: "Jump Rope",
    description: "Non-slip 6mm yoga mat.",
    images: [],
    favorite: false,
    price: 18.99,
    categoryId: "Sports Accessories",
    video: "",
  ),
  Product(
    id: "89",
    title: "Exercise Ball",
    description: "Non-slip 6mm yoga mat.",
    images: [],
    favorite: false,
    price: 18.99,
    categoryId: "Sports Accessories",
    video: "",
  ),

  // Sunglasses (46–48)
  Product(
    id: "90",
    title: "Aviator Sunglasses",
    description: "Classic metal-frame aviators.",
    images: [],
    favorite: false,
    price: 30.00,
    categoryId: "Sunglasses",
    video: "",
  ),
  Product(
    id: "91",
    title: "Polarized Driving Sunglasses",
    description: "Anti-glare polarized lenses.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Sunglasses",
    video: "",
  ),
  Product(
    id: "92",
    title: "Sports Sunglasses",
    description: "Lightweight wraparound sports glasses.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Sunglasses",
    video: "",
  ),
  Product(
    id: "93",
    title: "Round Frame Sunglasses",
    description: "Lightweight wraparound sports glasses.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Sunglasses",
    video: "",
  ),
  Product(
    id: "94",
    title: "Cat Eye Sunglasses",
    description: "Lightweight wraparound sports glasses.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Sunglasses",
    video: "",
  ),
  Product(
    id: "95",
    title: "Mirror Lens Sunglasses",
    description: "Lightweight wraparound sports glasses.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Sunglasses",
    video: "",
  ),

  // Tablets (49–51)
  Product(
    id: "96",
    title: "Tablet Pro 10",
    description: "10-inch professional productivity tablet.",
    images: [],
    favorite: false,
    price: 499.00,
    categoryId: "Tablets",
    video: "",
  ),
  Product(
    id: "97",
    title: "Kids Learning Tablet",
    description: "Durable educational tablet for kids.",
    images: [],
    favorite: false,
    price: 150.00,
    categoryId: "Tablets",
    video: "",
  ),
  Product(
    id: "98",
    title: "Compact Media Tablet",
    description: "8-inch tablet for entertainment.",
    images: [],
    favorite: false,
    price: 179.00,
    categoryId: "Tablets",
    video: "",
  ),
  Product(
    id: "99",
    title: "Drawing Tablet X",
    description: "8-inch tablet for entertainment.",
    images: [],
    favorite: false,
    price: 179.00,
    categoryId: "Tablets",
    video: "",
  ),
  Product(
    id: "100",
    title: "Business Tablet 12",
    description: "8-inch tablet for entertainment.",
    images: [],
    favorite: false,
    price: 179.00,
    categoryId: "Tablets",
    video: "",
  ),
  Product(
    id: "101",
    title: "Mini Tablet 7",
    description: "8-inch tablet for entertainment.",
    images: [],
    favorite: false,
    price: 179.00,
    categoryId: "Tablets",
    video: "",
  ),

  // Tops (52–54)
  Product(
    id: "102",
    title: "Cotton Casual Top",
    description: "Soft cotton top for women.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Tops",
    video: "",
  ),
  Product(
    id: "103",
    title: "Sleeveless Tank Top",
    description: "Lightweight summer tank top.",
    images: [],
    favorite: false,
    price: 8.99,
    categoryId: "Tops",
    video: "",
  ),
  Product(
    id: "104",
    title: "Long Sleeve Blouse",
    description: "Elegant blouse for casual outings.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Tops",
    video: "",
  ),
  Product(
    id: "105",
    title: "Printed Crop Top",
    description: "Elegant blouse for casual outings.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Tops",
    video: "",
  ),
  Product(
    id: "106",
    title: "Knitted Sweater",
    description: "Elegant blouse for casual outings.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Tops",
    video: "",
  ),
  Product(
    id: "107",
    title: "Silk Camisole",
    description: "Elegant blouse for casual outings.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Tops",
    video: "",
  ),

  // Vehicle (55–57)
  Product(
    id: "108",
    title: "Car Vacuum Cleaner",
    description: "Portable vacuum cleaner for vehicles.",
    images: [],
    favorite: false,
    price: 25.00,
    categoryId: "Vehicle",
    video: "",
  ),
  Product(
    id: "109",
    title: "Car Dashboard Perfume",
    description: "Long-lasting gel perfume for cars.",
    images: [],
    favorite: false,
    price: 6.50,
    categoryId: "Vehicle",
    video: "",
  ),
  Product(
    id: "110",
    title: "Car Phone Holder",
    description: "Rotating dashboard phone mount.",
    images: [],
    favorite: false,
    price: 9.99,
    categoryId: "Vehicle",
    video: "",
  ),
  Product(
    id: "111",
    title: "Car Seat Organizer",
    description: "Rotating dashboard phone mount.",
    images: [],
    favorite: false,
    price: 9.99,
    categoryId: "Vehicle",
    video: "",
  ),
  Product(
    id: "112",
    title: "Car Sunshade",
    description: "Rotating dashboard phone mount.",
    images: [],
    favorite: false,
    price: 9.99,
    categoryId: "Vehicle",
    video: "",
  ),
  Product(
    id: "113",
    title: "Car Jump Starter",
    description: "Rotating dashboard phone mount.",
    images: [],
    favorite: false,
    price: 9.99,
    categoryId: "Vehicle",
    video: "",
  ),

  // Womens Bags (58–60)
  Product(
    id: "114",
    title: "Leather Handbag",
    description: "Elegant premium leather handbag.",
    images: [],
    favorite: false,
    price: 65.00,
    categoryId: "Womens Bags",
    video: "",
  ),
  Product(
    id: "115",
    title: "Crossbody Bag",
    description: "Lightweight crossbody bag.",
    images: [],
    favorite: false,
    price: 32.00,
    categoryId: "Womens Bags",
    video: "",
  ),
  Product(
    id: "116",
    title: "Travel Tote Bag",
    description: "Large durable tote for travel.",
    images: [],
    favorite: false,
    price: 40.00,
    categoryId: "Womens Bags",
    video: "",
  ),
  Product(
    id: "117",
    title: "Mini Shoulder Bag",
    description: "Large durable tote for travel.",
    images: [],
    favorite: false,
    price: 40.00,
    categoryId: "Womens Bags",
    video: "",
  ),
  Product(
    id: "118",
    title: "Clutch Bag",
    description: "Large durable tote for travel.",
    images: [],
    favorite: false,
    price: 40.00,
    categoryId: "Womens Bags",
    video: "",
  ),
  Product(
    id: "119",
    title: "Backpack Purse",
    description: "Large durable tote for travel.",
    images: [],
    favorite: false,
    price: 40.00,
    categoryId: "Womens Bags",
    video: "",
  ),

  // Womens Dresses (61–63)
  Product(
    id: "120",
    title: "Floral Summer Dress",
    description: "Light and comfortable floral dress.",
    images: [],
    favorite: false,
    price: 28.00,
    categoryId: "Womens Dresses",
    video: "",
  ),
  Product(
    id: "121",
    title: "Evening Gown",
    description: "Elegant long gown for special events.",
    images: [],
    favorite: false,
    price: 75.00,
    categoryId: "Womens Dresses",
    video: "",
  ),
  Product(
    id: "122",
    title: "Casual Midi Dress",
    description: "Comfortable midi-length dress.",
    images: [],
    favorite: false,
    price: 30.00,
    categoryId: "Womens Dresses",
    video: "",
  ),
  Product(
    id: "123",
    title: "Bodycon Dress",
    description: "Comfortable midi-length dress.",
    images: [],
    favorite: false,
    price: 30.00,
    categoryId: "Womens Dresses",
    video: "",
  ),
  Product(
    id: "124",
    title: "Maxi Dress",
    description: "Comfortable midi-length dress.",
    images: [],
    favorite: false,
    price: 30.00,
    categoryId: "Womens Dresses",
    video: "",
  ),
  Product(
    id: "125",
    title: "Shirt Dress",
    description: "Comfortable midi-length dress.",
    images: [],
    favorite: false,
    price: 30.00,
    categoryId: "Womens Dresses",
    video: "",
  ),

  // Womens Jewellery (64–66)
  Product(
    id: "126",
    title: "Gold-Plated Necklace",
    description: "Beautiful gold-plated necklace.",
    images: [],
    favorite: false,
    price: 20.00,
    categoryId: "Womens Jewellery",
    video: "",
  ),
  Product(
    id: "127",
    title: "Silver Bracelet",
    description: "Elegant sterling silver bracelet.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Womens Jewellery",
    video: "",
  ),
  Product(
    id: "128",
    title: "Diamond Stud Earrings",
    description: "Classic diamond stud earrings.",
    images: [],
    favorite: false,
    price: 49.00,
    categoryId: "Womens Jewellery",
    video: "",
  ),
  Product(
    id: "129",
    title: "Pearl Pendant Necklace",
    description: "Classic diamond stud earrings.",
    images: [],
    favorite: false,
    price: 49.00,
    categoryId: "Womens Jewellery",
    video: "",
  ),
  Product(
    id: "130",
    title: "Charm Bracelet",
    description: "Classic diamond stud earrings.",
    images: [],
    favorite: false,
    price: 49.00,
    categoryId: "Womens Jewellery",
    video: "",
  ),
  Product(
    id: "131",
    title: "Hoop Earrings Set",
    description: "Classic diamond stud earrings.",
    images: [],
    favorite: false,
    price: 49.00,
    categoryId: "Womens Jewellery",
    video: "",
  ),

  // Womens Shoes (67–69)
  Product(
    id: "132",
    title: "High Heels",
    description: "Stylish high heels for parties.",
    images: [],
    favorite: false,
    price: 35.00,
    categoryId: "Womens Shoes",
    video: "",
  ),
  Product(
    id: "133",
    title: "Running Shoes",
    description: "Comfortable running shoes for women.",
    images: [],
    favorite: false,
    price: 50.00,
    categoryId: "Womens Shoes",
    video: "",
  ),
  Product(
    id: "134",
    title: "Casual Flats",
    description: "Lightweight everyday flat shoes.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Womens Shoes",
    video: "",
  ),
  Product(
    id: "135",
    title: "Ankle Boots",
    description: "Lightweight everyday flat shoes.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Womens Shoes",
    video: "",
  ),
  Product(
    id: "136",
    title: "Sandals",
    description: "Lightweight everyday flat shoes.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Womens Shoes",
    video: "",
  ),
  Product(
    id: "137",
    title: "Ballet Flats",
    description: "Lightweight everyday flat shoes.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Womens Shoes",
    video: "",
  ),

  // Womens Watches (70)
  Product(
    id: "138",
    title: "Rose Gold Watch",
    description: "Stylish rose gold wristwatch for women.",
    images: [],
    favorite: false,
    price: 55.00,
    categoryId: "Womens Watches",
    video: "",
  ),
  Product(
    id: "139",
    title: "Silver Bracelet Watch",
    description: "Stylish rose gold wristwatch for women.",
    images: [],
    favorite: false,
    price: 55.00,
    categoryId: "Womens Watches",
    video: "",
  ),
  Product(
    id: "140",
    title: "Digital Fitness Watch",
    description: "Stylish rose gold wristwatch for women.",
    images: [],
    favorite: false,
    price: 55.00,
    categoryId: "Womens Watches",
    video: "",
  ),
  Product(
    id: "141",
    title: "Leather Strap Watch",
    description: "Stylish rose gold wristwatch for women.",
    images: [],
    favorite: false,
    price: 55.00,
    categoryId: "Womens Watches",
    video: "",
  ),
  Product(
    id: "142",
    title: "Minimalist White Watch",
    description: "Stylish rose gold wristwatch for women.",
    images: [],
    favorite: false,
    price: 55.00,
    categoryId: "Womens Watches",
    video: "",
  ),
  Product(
    id: "143",
    title: "Gold Accent Watch",
    description: "Stylish rose gold wristwatch for women.",
    images: [],
    favorite: false,
    price: 55.00,
    categoryId: "Womens Watches",
    video: "",
  ),
];
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
final List<Product> arabicProducts = [
  // Beauty (1–3)
  Product(
    id: "0",
    title: "كريم ترطيب للوجه",
    description: "مرطب خفيف للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 12.99,
    categoryId: "Beauty",
    video: "",
  ),
  Product(
    id: "1",
    title: "سيروم فيتامين سي",
    description: "سيروم لتفتيح البشرة ومنحها إشراقة.",
    images: [],
    favorite: false,
    price: 18.50,
    categoryId: "Beauty",
    video: "",
  ),
  Product(
    id: "2",
    title: "مجموعة فراشي مكياج",
    description: "طقم مكون من 12 فرشاة مكياج عالية الجودة.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Beauty",
    video: "",
  ),
  Product(
    id: "900",
    title: "كريم الليل التجديدي",
    description: "طقم مكون من 12 فرشاة مكياج عالية الجودة.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Beauty",
    video: "",
  ),
  Product(
    id: "4",
    title: "مقشر الوجه",
    description: "طقم مكون من 12 فرشاة مكياج عالية الجودة.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Beauty",
    video: "",
  ),
  Product(
    id: "5",
    title: "طقم بلسم الشفاه",
    description: "طقم مكون من 12 فرشاة مكياج عالية الجودة.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Beauty",
    video: "",
  ),

  // Fragrances (4–6)
  Product(
    id: "6",
    title: "عطر نسيم البحر",
    description: "رائحة منعشة مناسبة للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 35.00,
    categoryId: "Fragrances",
    video: "",
  ),
  Product(
    id: "7",
    title: "عطر أمبر وود",
    description: "مزيج دافئ من الأخشاب والعنبر.",
    images: [],
    favorite: false,
    price: 49.99,
    categoryId: "Fragrances",
    video: "",
  ),
  Product(
    id: "8",
    title: "رذاذ زهري للجسم",
    description: "معطر جسم برائحة زهرية لطيفة.",
    images: [],
    favorite: false,
    price: 14.99,
    categoryId: "Fragrances",
    video: "",
  ),
  Product(
    id: "9",
    title: "عطر الحمضيات",
    description: "معطر جسم برائحة زهرية لطيفة.",
    images: [],
    favorite: false,
    price: 14.99,
    categoryId: "Fragrances",
    video: "",
  ),
  Product(
    id: "10",
    title: "عطر جوهر الورد",
    description: "معطر جسم برائحة زهرية لطيفة.",
    images: [],
    favorite: false,
    price: 14.99,
    categoryId: "Fragrances",
    video: "",
  ),
  Product(
    id: "11",
    title: "رذاذ الفانيليا والتوابل",
    description: "معطر جسم برائحة زهرية لطيفة.",
    images: [],
    favorite: false,
    price: 14.99,
    categoryId: "Fragrances",
    video: "",
  ),

  // Furniture (7–9)
  Product(
    id: "12",
    title: "كنبة مودرن",
    description: "كنبة ثلاثية بمظهر عصري وأرجل خشبية.",
    images: [],
    favorite: false,
    price: 450.00,
    categoryId: "Furniture",
    video: "",
  ),
  Product(
    id: "13",
    title: "طاولة قهوة خشبية",
    description: "طاولة قهوة بسيطة من خشب البلوط.",
    images: [],
    favorite: false,
    price: 120.00,
    categoryId: "Furniture",
    video: "",
  ),
  Product(
    id: "14",
    title: "كرسي مكتب",
    description: "كرسي مريح بارتفاع قابل للتعديل.",
    images: [],
    favorite: false,
    price: 99.99,
    categoryId: "Furniture",
    video: "",
  ),
  Product(
    id: "15",
    title: "وحدة رفوف للكتب",
    description: "كرسي مريح بارتفاع قابل للتعديل.",
    images: [],
    favorite: false,
    price: 99.99,
    categoryId: "Furniture",
    video: "",
  ),
  Product(
    id: "16",
    title: "طقم طاولة طعام",
    description: "كرسي مريح بارتفاع قابل للتعديل.",
    images: [],
    favorite: false,
    price: 99.99,
    categoryId: "Furniture",
    video: "",
  ),
  Product(
    id: "17",
    title: "خزانة تلفاز",
    description: "كرسي مريح بارتفاع قابل للتعديل.",
    images: [],
    favorite: false,
    price: 99.99,
    categoryId: "Furniture",
    video: "",
  ),

  // Groceries (10–12)
  Product(
    id: "18",
    title: "أرز بني عضوي",
    description: "كيس 1 كجم من الأرز البني الصحي.",
    images: [],
    favorite: false,
    price: 5.99,
    categoryId: "Groceries",
    video: "",
  ),
  Product(
    id: "19",
    title: "زيت زيتون بكر ممتاز",
    description: "زيت زيتون معصور على البارد بحجم 500 مل.",
    images: [],
    favorite: false,
    price: 8.99,
    categoryId: "Groceries",
    video: "",
  ),
  Product(
    id: "20",
    title: "حبوب قهوة عربية",
    description: "حبوب قهوة محمصة عالية الجودة، 1 كجم.",
    images: [],
    favorite: false,
    price: 15.50,
    categoryId: "Groceries",
    video: "",
  ),
  Product(
    id: "21",
    title: "مكرونة من القمح الكامل",
    description: "حبوب قهوة محمصة عالية الجودة، 1 كجم.",
    images: [],
    favorite: false,
    price: 15.50,
    categoryId: "Groceries",
    video: "",
  ),
  Product(
    id: "22",
    title: "عسل طبيعي",
    description: "حبوب قهوة محمصة عالية الجودة، 1 كجم.",
    images: [],
    favorite: false,
    price: 15.50,
    categoryId: "Groceries",
    video: "",
  ),
  Product(
    id: "23",
    title: "لوز عضوي",
    description: "حبوب قهوة محمصة عالية الجودة، 1 كجم.",
    images: [],
    favorite: false,
    price: 15.50,
    categoryId: "Groceries",
    video: "",
  ),

  // Home Decoration (13–15)
  Product(
    id: "24",
    title: "لوحة فنية جدارية",
    description: "لوحة بطابع مجرد عصري.",
    images: [],
    favorite: false,
    price: 40.00,
    categoryId: "Home Decoration",
    video: "",
  ),
  Product(
    id: "25",
    title: "فازة ديكور",
    description: "فازة سيراميك بطبقة لامعة.",
    images: [],
    favorite: false,
    price: 25.00,
    categoryId: "Home Decoration",
    video: "",
  ),
  Product(
    id: "26",
    title: "سلسلة إضاءة LED",
    description: "إضاءة خيطية دافئة للديكور.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Home Decoration",
    video: "",
  ),
  Product(
    id: "27",
    title: "وعاء نبات داخلي",
    description: "إضاءة خيطية دافئة للديكور.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Home Decoration",
    video: "",
  ),
  Product(
    id: "28",
    title: "مرآة جدارية زخرفية",
    description: "إضاءة خيطية دافئة للديكور.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Home Decoration",
    video: "",
  ),
  Product(
    id: "29",
    title: "طقم شموع عطرية",
    description: "إضاءة خيطية دافئة للديكور.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Home Decoration",
    video: "",
  ),

  // Kitchen Accessories (16–18)
  Product(
    id: "30",
    title: "طقم سكاكين مطبخ",
    description: "طقم احترافي مكون من 5 سكاكين.",
    images: [],
    favorite: false,
    price: 32.00,
    categoryId: "Kitchen Accessories",
    video: "",
  ),
  Product(
    id: "31",
    title: "مقلاة غير لاصقة",
    description: "مقلاة 28 سم بطبقة سيراميك.",
    images: [],
    favorite: false,
    price: 18.99,
    categoryId: "Kitchen Accessories",
    video: "",
  ),
  Product(
    id: "32",
    title: "علب زجاج للطعام",
    description: "طقم مكون من 6 علب محكمة الإغلاق.",
    images: [],
    favorite: false,
    price: 20.00,
    categoryId: "Kitchen Accessories",
    video: "",
  ),
  Product(
    id: "33",
    title: "حصيرة خبز سيليكون",
    description: "طقم مكون من 6 علب محكمة الإغلاق.",
    images: [],
    favorite: false,
    price: 20.00,
    categoryId: "Kitchen Accessories",
    video: "",
  ),
  Product(
    id: "34",
    title: "غلاية كهربائية",
    description: "طقم مكون من 6 علب محكمة الإغلاق.",
    images: [],
    favorite: false,
    price: 20.00,
    categoryId: "Kitchen Accessories",
    video: "",
  ),
  Product(
    id: "35",
    title: "طقم أكواب قياس",
    description: "طقم مكون من 6 علب محكمة الإغلاق.",
    images: [],
    favorite: false,
    price: 20.00,
    categoryId: "Kitchen Accessories",
    video: "",
  ),

  // Laptops (19–21)
  Product(
    id: "36",
    title: "لابتوب ألترابوك برو 14",
    description: "لابتوب نحيف مقاس 14 بوصة مع 16 جيجا رام.",
    images: [],
    favorite: false,
    price: 899.00,
    categoryId: "Laptops",
    video: "",
  ),
  Product(
    id: "37",
    title: "لابتوب الألعاب X",
    description: "أداء عالي مع بطاقة RTX.",
    images: [],
    favorite: false,
    price: 1299.00,
    categoryId: "Laptops",
    video: "",
  ),
  Product(
    id: "38",
    title: "لابتوب خفيف الوزن لابتوب خفيف الوزن",
    description: "مثالي للطلاب والعمل اليومي.",
    images: [],
    favorite: false,
    price: 550.00,
    categoryId: "Laptops",
    video: "",
  ),
  Product(
    id: "39",
    title: "لاب توب أعمال برو",
    description: "مثالي للطلاب والعمل اليومي.",
    images: [],
    favorite: false,
    price: 550.00,
    categoryId: "Laptops",
    video: "",
  ),
  Product(
    id: "40",
    title: "لاب توب طالب 15",
    description: "مثالي للطلاب والعمل اليومي.",
    images: [],
    favorite: false,
    price: 550.00,
    categoryId: "Laptops",
    video: "",
  ),
  Product(
    id: "41",
    title: "لاب توب 2 في 1 قابل للتحويل",
    description: "مثالي للطلاب والعمل اليومي.",
    images: [],
    favorite: false,
    price: 550.00,
    categoryId: "Laptops",
    video: "",
  ),

  // Mens Shirts (22–24)
  Product(
    id: "42",
    title: "قميص قطني رجالي",
    description: "قميص قطن مناسب للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 19.99,
    categoryId: "Mens Shirts",
    video: "",
  ),
  Product(
    id: "43",
    title: "قميص رسمي أبيض",
    description: "قميص كلاسيكي للمناسبات الرسمية.",
    images: [],
    favorite: false,
    price: 25.00,
    categoryId: "Mens Shirts",
    video: "",
  ),
  Product(
    id: "44",
    title: "قميص فلانيل",
    description: "قميص شتوي بنقشة كاروهات.",
    images: [],
    favorite: false,
    price: 22.50,
    categoryId: "Mens Shirts",
    video: "",
  ),
  Product(
    id: "45",
    title: "قميص بولو مخطط",
    description: "قميص شتوي بنقشة كاروهات.",
    images: [],
    favorite: false,
    price: 22.50,
    categoryId: "Mens Shirts",
    video: "",
  ),
  Product(
    id: "46",
    title: "قميص جينز بأزرار",
    description: "قميص شتوي بنقشة كاروهات.",
    images: [],
    favorite: false,
    price: 22.50,
    categoryId: "Mens Shirts",
    video: "",
  ),
  Product(
    id: "47",
    title: "قميص صيفي كتان",
    description: "قميص شتوي بنقشة كاروهات.",
    images: [],
    favorite: false,
    price: 22.50,
    categoryId: "Mens Shirts",
    video: "",
  ),

  // Mens Shoes (25–27)
  Product(
    id: "48",
    title: "حذاء جري رجالي",
    description: "حذاء رياضي خفيف ومريح.",
    images: [],
    favorite: false,
    price: 55.00,
    categoryId: "Mens Shoes",
    video: "",
  ),
  Product(
    id: "49",
    title: "جزمة جلد رجالية",
    description: "جزمة جلدية متينة باللون البني.",
    images: [],
    favorite: false,
    price: 89.00,
    categoryId: "Mens Shoes",
    video: "",
  ),
  Product(
    id: "50",
    title: "حذاء لوفرز رجالي",
    description: "حذاء مريح مناسب للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 45.00,
    categoryId: "Mens Shoes",
    video: "",
  ),
  Product(
    id: "51",
    title: "حذاء رسمي",
    description: "حذاء مريح مناسب للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 45.00,
    categoryId: "Mens Shoes",
    video: "",
  ),
  Product(
    id: "52",
    title: "حذاء قماشي سهل الارتداء",
    description: "حذاء مريح مناسب للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 45.00,
    categoryId: "Mens Shoes",
    video: "",
  ),
  Product(
    id: "53",
    title: "حذاء عالي الكاحل رياضي",
    description: "حذاء مريح مناسب للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 45.00,
    categoryId: "Mens Shoes",
    video: "",
  ),

  // Mens Watches (28–30)
  Product(
    id: "54",
    title: "ساعة جلد كلاسيكية",
    description: "ساعة أنالوج بحزام جلدي.",
    images: [],
    favorite: false,
    price: 60.00,
    categoryId: "Mens Watches",
    video: "",
  ),
  Product(
    id: "55",
    title: "ساعة معدنية رجالية",
    description: "ساعة ستانلس ستيل مع عرض للتاريخ.",
    images: [],
    favorite: false,
    price: 75.00,
    categoryId: "Mens Watches",
    video: "",
  ),
  Product(
    id: "56",
    title: "ساعة رياضية رقمية",
    description: "ساعة رقمية مقاومة للماء مع مؤقت.",
    images: [],
    favorite: false,
    price: 35.00,
    categoryId: "Mens Watches",
    video: "",
  ),
  Product(
    id: "57",
    title: "ساعة كرونوغراف",
    description: "ساعة رقمية مقاومة للماء مع مؤقت.",
    images: [],
    favorite: false,
    price: 35.00,
    categoryId: "Mens Watches",
    video: "",
  ),
  Product(
    id: "58",
    title: "ساعة أنيقة رسمية",
    description: "ساعة رقمية مقاومة للماء مع مؤقت.",
    images: [],
    favorite: false,
    price: 35.00,
    categoryId: "Mens Watches",
    video: "",
  ),
  Product(
    id: "59",
    title: "ساعة ذكية",
    description: "ساعة رقمية مقاومة للماء مع مؤقت.",
    images: [],
    favorite: false,
    price: 35.00,
    categoryId: "Mens Watches",
    video: "",
  ),

  // Mobile Accessories (31–33)
  Product(
    id: "60",
    title: "كابل شحن سريع",
    description: "كابل USB-C بطول 1 متر.",
    images: [],
    favorite: false,
    price: 5.99,
    categoryId: "Mobile Accessories",
    video: "",
  ),
  Product(
    id: "61",
    title: "شاحن لاسلكي",
    description: "لوحة شحن لاسلكية معتمدة.",
    images: [],
    favorite: false,
    price: 19.99,
    categoryId: "Mobile Accessories",
    video: "",
  ),
  Product(
    id: "62",
    title: "حامل موبايل ثلاثي",
    description: "حامل هاتف صغير للتصوير.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Mobile Accessories",
    video: "",
  ),
  Product(
    id: "63",
    title: "واقي شاشة زجاجي",
    description: "حامل هاتف صغير للتصوير.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Mobile Accessories",
    video: "",
  ),
  Product(
    id: "64",
    title: "غطاء هاتف سيليكون",
    description: "حامل هاتف صغير للتصوير.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Mobile Accessories",
    video: "",
  ),
  Product(
    id: "65",
    title: "حامل سيارة للهاتف",
    description: "حامل هاتف صغير للتصوير.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Mobile Accessories",
    video: "",
  ),

  // Motorcycle (34–36)
  Product(
    id: "66",
    title: "خوذة موتوسيكل",
    description: "خوذة حماية كاملة عالية الجودة.",
    images: [],
    favorite: false,
    price: 85.00,
    categoryId: "Motorcycle",
    video: "",
  ),
  Product(
    id: "67",
    title: "قفازات قيادة",
    description: "قفازات حماية مناسبة للقيادة.",
    images: [],
    favorite: false,
    price: 20.00,
    categoryId: "Motorcycle",
    video: "",
  ),
  Product(
    id: "68",
    title: "حامل موبايل للدراجة",
    description: "حامل قوي لتثبيت الهاتف على الدراجة.",
    images: [],
    favorite: false,
    price: 10.00,
    categoryId: "Motorcycle",
    video: "",
  ),
  Product(
    id: "69",
    title: "سترة واقية",
    description: "حامل قوي لتثبيت الهاتف على الدراجة.",
    images: [],
    favorite: false,
    price: 10.00,
    categoryId: "Motorcycle",
    video: "",
  ),
  Product(
    id: "70",
    title: "أحذية ركوب الدراجة",
    description: "حامل قوي لتثبيت الهاتف على الدراجة.",
    images: [],
    favorite: false,
    price: 10.00,
    categoryId: "Motorcycle",
    video: "",
  ),
  Product(
    id: "71",
    title: "أضواء إشارة للدراجة",
    description: "حامل قوي لتثبيت الهاتف على الدراجة.",
    images: [],
    favorite: false,
    price: 10.00,
    categoryId: "Motorcycle",
    video: "",
  ),

  // Skin Care (37–39)
  Product(
    id: "72",
    title: "جل ألوفيرا",
    description: "جل مهدئ لترطيب البشرة.",
    images: [],
    favorite: false,
    price: 9.99,
    categoryId: "Skin Care",
    video: "",
  ),
  Product(
    id: "73",
    title: "واقي شمس SPF 50",
    description: "حماية واسعة المدى من أشعة الشمس.",
    images: [],
    favorite: false,
    price: 14.50,
    categoryId: "Skin Care",
    video: "",
  ),
  Product(
    id: "74",
    title: "غسول وجه رغوي",
    description: "غسول لطيف للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 7.99,
    categoryId: "Skin Care",
    video: "",
  ),
  Product(
    id: "75",
    title: "قناع الطين",
    description: "غسول لطيف للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 7.99,
    categoryId: "Skin Care",
    video: "",
  ),
  Product(
    id: "76",
    title: "مرطب ليلي مغذي",
    description: "غسول لطيف للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 7.99,
    categoryId: "Skin Care",
    video: "",
  ),
  Product(
    id: "77",
    title: "سيروم مضاد للتجاعيد",
    description: "غسول لطيف للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 7.99,
    categoryId: "Skin Care",
    video: "",
  ),

  // Smartphones (40–42)
  Product(
    id: "78",
    title: "هاتف X12",
    description: "هاتف بشاشة 6.5 بوصة وبطارية قوية.",
    images: [],
    favorite: false,
    price: 450.00,
    categoryId: "Smartphones",
    video: "",
  ),
  Product(
    id: "79",
    title: "هاتف Nova A9",
    description: "هاتف متوسط بقدرات تصوير ممتازة.",
    images: [],
    favorite: false,
    price: 320.00,
    categoryId: "Smartphones",
    video: "",
  ),
  Product(
    id: "80",
    title: "هاتف Mini Lite",
    description: "هاتف صغير الحجم مع شحن سريع.",
    images: [],
    favorite: false,
    price: 219.00,
    categoryId: "Smartphones",
    video: "",
  ),
  Product(
    id: "81",
    title: "هاتف ألعاب 5G",
    description: "هاتف صغير الحجم مع شحن سريع.",
    images: [],
    favorite: false,
    price: 219.00,
    categoryId: "Smartphones",
    video: "",
  ),
  Product(
    id: "82",
    title: "هاتف كاميرا احترافية",
    description: "هاتف صغير الحجم مع شحن سريع.",
    images: [],
    favorite: false,
    price: 219.00,
    categoryId: "Smartphones",
    video: "",
  ),
  Product(
    id: "83",
    title: "هاتف اقتصادي",
    description: "هاتف صغير الحجم مع شحن سريع.",
    images: [],
    favorite: false,
    price: 219.00,
    categoryId: "Smartphones",
    video: "",
  ),

  // Sports Accessories (43–45)
  Product(
    id: "84",
    title: "مجموعة مطاطات رياضية",
    description: "مجموعة من 5 مطاطات لتمارين القوة.",
    images: [],
    favorite: false,
    price: 15.00,
    categoryId: "Sports Accessories",
    video: "",
  ),
  Product(
    id: "85",
    title: "كرة قدم",
    description: "كرة قدم بجودة المباريات.",
    images: [],
    favorite: false,
    price: 25.00,
    categoryId: "Sports Accessories",
    video: "",
  ),
  Product(
    id: "86",
    title: "حصيرة يوغا",
    description: "حصيرة يوغا 6 مم غير قابلة للانزلاق.",
    images: [],
    favorite: false,
    price: 18.99,
    categoryId: "Sports Accessories",
    video: "",
  ),
  Product(
    id: "87",
    title: "قفازات ملاكمة",
    description: "حصيرة يوغا 6 مم غير قابلة للانزلاق.",
    images: [],
    favorite: false,
    price: 18.99,
    categoryId: "Sports Accessories",
    video: "",
  ),
  Product(
    id: "88",
    title: "أوزان يد صغيرة",
    description: "حصيرة يوغا 6 مم غير قابلة للانزلاق.",
    images: [],
    favorite: false,
    price: 18.99,
    categoryId: "Sports Accessories",
    video: "",
  ),
  Product(
    id: "89",
    title: "حبل قفز",
    description: "حصيرة يوغا 6 مم غير قابلة للانزلاق.",
    images: [],
    favorite: false,
    price: 18.99,
    categoryId: "Sports Accessories",
    video: "",
  ),

  // Sunglasses (46–48)
  Product(
    id: "90",
    title: "نظارة شمسية طيار",
    description: "نظارة بإطار معدني كلاسيكي.",
    images: [],
    favorite: false,
    price: 30.00,
    categoryId: "Sunglasses",
    video: "",
  ),
  Product(
    id: "91",
    title: "نظارة قيادة مضادة للوهج",
    description: "عدسات مستقطبة لتقليل الانعكاس.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Sunglasses",
    video: "",
  ),
  Product(
    id: "92",
    title: "نظارة رياضية",
    description: "نظارة خفيفة مخصصة للرياضة.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Sunglasses",
    video: "",
  ),
  Product(
    id: "93",
    title: "نظارات شمسية عصرية",
    description: "نظارة خفيفة مخصصة للرياضة.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Sunglasses",
    video: "",
  ),
  Product(
    id: "94",
    title: "نظارات إطار بلاستيكي",
    description: "نظارة خفيفة مخصصة للرياضة.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Sunglasses",
    video: "",
  ),
  Product(
    id: "95",
    title: "نظارات مقاومة الأشعة",
    description: "نظارة خفيفة مخصصة للرياضة.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Sunglasses",
    video: "",
  ),

  // Tablets (49–51)
  Product(
    id: "96",
    title: "جهاز لوحي Pro 10",
    description: "جهاز لوحي مقاس 10 بوصة للعمل والإنتاجية.",
    images: [],
    favorite: false,
    price: 499.00,
    categoryId: "Tablets",
    video: "",
  ),
  Product(
    id: "97",
    title: "تابلت تعليمي للأطفال",
    description: "تابلت قوي ومتين مخصص للأطفال.",
    images: [],
    favorite: false,
    price: 150.00,
    categoryId: "Tablets",
    video: "",
  ),
  Product(
    id: "98",
    title: "تابلت ميديا صغير",
    description: "تابلت مقاس 8 بوصة للترفيه.",
    images: [],
    favorite: false,
    price: 179.00,
    categoryId: "Tablets",
    video: "",
  ),
  Product(
    id: "99",
    title: "تابلت ألعاب",
    description: "تابلت مقاس 8 بوصة للترفيه.",
    images: [],
    favorite: false,
    price: 179.00,
    categoryId: "Tablets",
    video: "",
  ),
  Product(
    id: "100",
    title: "تابلت للرسم الرقمي",
    description: "تابلت مقاس 8 بوصة للترفيه.",
    images: [],
    favorite: false,
    price: 179.00,
    categoryId: "Tablets",
    video: "",
  ),
  Product(
    id: "101",
    title: "تابلت مكتبي",
    description: "تابلت مقاس 8 بوصة للترفيه.",
    images: [],
    favorite: false,
    price: 179.00,
    categoryId: "Tablets",
    video: "",
  ),

  // Tops (52–54)
  Product(
    id: "102",
    title: "توب قطن نسائي",
    description: "توب ناعم ومريح للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 12.00,
    categoryId: "Tops",
    video: "",
  ),
  Product(
    id: "103",
    title: "توب كت صيفي",
    description: "توب خفيف مناسب لفصل الصيف.",
    images: [],
    favorite: false,
    price: 8.99,
    categoryId: "Tops",
    video: "",
  ),
  Product(
    id: "104",
    title: "بلوزة كم طويل",
    description: "بلوزة أنيقة مناسبة للخروج.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Tops",
    video: "",
  ),
  Product(
    id: "105",
    title: "توب حريري رسمي",
    description: "بلوزة أنيقة مناسبة للخروج.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Tops",
    video: "",
  ),
  Product(
    id: "106",
    title: "توب رياضي",
    description: "بلوزة أنيقة مناسبة للخروج.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Tops",
    video: "",
  ),
  Product(
    id: "107",
    title: "توب صيفي مزخرف",
    description: "بلوزة أنيقة مناسبة للخروج.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Tops",
    video: "",
  ),

  // Vehicle (55–57)
  Product(
    id: "108",
    title: "مكنسة سيارات",
    description: "مكنسة كهربائية محمولة للسيارة.",
    images: [],
    favorite: false,
    price: 25.00,
    categoryId: "Vehicle",
    video: "",
  ),
  Product(
    id: "109",
    title: "معطر تابلوه للسيارة",
    description: "معطر جل برائحة تدوم طويلاً.",
    images: [],
    favorite: false,
    price: 6.50,
    categoryId: "Vehicle",
    video: "",
  ),
  Product(
    id: "110",
    title: "حامل هاتف للسيارة",
    description: "حامل دوّار لتثبيت الهاتف على التابلوه.",
    images: [],
    favorite: false,
    price: 9.99,
    categoryId: "Vehicle",
    video: "",
  ),
  Product(
    id: "111",
    title: "مظلة سيارة",
    description: "حامل دوّار لتثبيت الهاتف على التابلوه.",
    images: [],
    favorite: false,
    price: 9.99,
    categoryId: "Vehicle",
    video: "",
  ),
  Product(
    id: "112",
    title: "وسادة دعم للسيارة",
    description: "حامل دوّار لتثبيت الهاتف على التابلوه.",
    images: [],
    favorite: false,
    price: 9.99,
    categoryId: "Vehicle",
    video: "",
  ),
  Product(
    id: "113",
    title: "غطاء مقعد السيارة",
    description: "حامل دوّار لتثبيت الهاتف على التابلوه.",
    images: [],
    favorite: false,
    price: 9.99,
    categoryId: "Vehicle",
    video: "",
  ),

  // Womens Bags (58–60)
  Product(
    id: "114",
    title: "شنطة يد جلد",
    description: "شنطة يد أنيقة من الجلد الطبيعي.",
    images: [],
    favorite: false,
    price: 65.00,
    categoryId: "Womens Bags",
    video: "",
  ),
  Product(
    id: "115",
    title: "شنطة كروس",
    description: "شنطة خفيفة بتصميم مريح.",
    images: [],
    favorite: false,
    price: 32.00,
    categoryId: "Womens Bags",
    video: "",
  ),
  Product(
    id: "116",
    title: "شنطة سفر كبيرة",
    description: "شنطة واسعة ومتينة للسفر.",
    images: [],
    favorite: false,
    price: 40.00,
    categoryId: "Womens Bags",
    video: "",
  ),
  Product(
    id: "117",
    title: "حقيبة صغيرة مسائية",
    description: "شنطة واسعة ومتينة للسفر.",
    images: [],
    favorite: false,
    price: 40.00,
    categoryId: "Womens Bags",
    video: "",
  ),
  Product(
    id: "118",
    title: "حقيبة ظهر أنيقة",
    description: "شنطة واسعة ومتينة للسفر.",
    images: [],
    favorite: false,
    price: 40.00,
    categoryId: "Womens Bags",
    video: "",
  ),
  Product(
    id: "119",
    title: "حقيبة شاطئية",
    description: "شنطة واسعة ومتينة للسفر.",
    images: [],
    favorite: false,
    price: 40.00,
    categoryId: "Womens Bags",
    video: "",
  ),

  // Womens Dresses (61–63)
  Product(
    id: "120",
    title: "فستان صيفي مزهر",
    description: "فستان خفيف ومريح مناسب للصيف.",
    images: [],
    favorite: false,
    price: 28.00,
    categoryId: "IWomens Dresses",
    video: "",
  ),
  Product(
    id: "121",
    title: "فستان سهرة",
    description: "فستان أنيق للمناسبات الخاصة.",
    images: [],
    favorite: false,
    price: 75.00,
    categoryId: "IWomens Dresses",
    video: "",
  ),
  Product(
    id: "122",
    title: "فستان ميدي كاجوال",
    description: "فستان مريح بطول متوسط.",
    images: [],
    favorite: false,
    price: 30.00,
    categoryId: "IWomens Dresses",
    video: "",
  ),
  Product(
    id: "123",
    title: "فستان مكتب رسمي",
    description: "فستان مريح بطول متوسط.",
    images: [],
    favorite: false,
    price: 30.00,
    categoryId: "IWomens Dresses",
    video: "",
  ),
  Product(
    id: "124",
    title: "فستان سهرة قصير",
    description: "فستان مريح بطول متوسط.",
    images: [],
    favorite: false,
    price: 30.00,
    categoryId: "IWomens Dresses",
    video: "",
  ),
  Product(
    id: "125",
    title: "فستان كاجوال فضفاض",
    description: "فستان مريح بطول متوسط.",
    images: [],
    favorite: false,
    price: 30.00,
    categoryId: "IWomens Dresses",
    video: "",
  ),

  // Womens Jewellery (64–66)
  Product(
    id: "126",
    title: "عقد مطلي بالذهب",
    description: "عقد أنيق مطلي بالذهب.",
    images: [],
    favorite: false,
    price: 20.00,
    categoryId: "Womens Jewellery",
    video: "",
  ),
  Product(
    id: "127",
    title: "إسوارة فضية",
    description: "إسوارة فضية أنيقة.",
    images: [],
    favorite: false,
    price: 18.00,
    categoryId: "Womens Jewellery",
    video: "",
  ),
  Product(
    id: "128",
    title: "حلق ماس صغير",
    description: "أقراط ماس كلاسيكية.",
    images: [],
    favorite: false,
    price: 49.00,
    categoryId: "Womens Jewellery",
    video: "",
  ),
  Product(
    id: "129",
    title: "خاتم فضي",
    description: "أقراط ماس كلاسيكية.",
    images: [],
    favorite: false,
    price: 49.00,
    categoryId: "Womens Jewellery",
    video: "",
  ),
  Product(
    id: "130",
    title: "أساور متعددة الطبقات",
    description: "أقراط ماس كلاسيكية.",
    images: [],
    favorite: false,
    price: 49.00,
    categoryId: "Womens Jewellery",
    video: "",
  ),
  Product(
    id: "131",
    title: "سلسلة ذهبية بسيطة",
    description: "أقراط ماس كلاسيكية.",
    images: [],
    favorite: false,
    price: 49.00,
    categoryId: "Womens Jewellery",
    video: "",
  ),

  // Womens Shoes (67–69)
  Product(
    id: "132",
    title: "كعب عالي نسائي",
    description: "حذاء بكعب عالي للمناسبات.",
    images: [],
    favorite: false,
    price: 35.00,
    categoryId: "Womens Shoes",
    video: "",
  ),
  Product(
    id: "133",
    title: "حذاء جري نسائي",
    description: "حذاء مريح للتمارين والجري.",
    images: [],
    favorite: false,
    price: 50.00,
    categoryId: "Womens Shoes",
    video: "",
  ),
  Product(
    id: "134",
    title: "حذاء فلات نسائي",
    description: "حذاء خفيف للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Womens Shoes",
    video: "",
  ),
  Product(
    id: "135",
    title: "صندل صيفي",
    description: "حذاء خفيف للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Womens Shoes",
    video: "",
  ),
  Product(
    id: "136",
    title: "حذاء رسمي نسائي",
    description: "حذاء خفيف للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Womens Shoes",
    video: "",
  ),
  Product(
    id: "137",
    title: "حذاء بوت أنيق",
    description: "حذاء خفيف للاستخدام اليومي.",
    images: [],
    favorite: false,
    price: 22.00,
    categoryId: "Womens Shoes",
    video: "",
  ),

  // Womens Watches (70)
  Product(
    id: "138",
    title: "ساعة روز جولد نسائية",
    description: "ساعة نسائية أنيقة بلون روز جولد.",
    images: [],
    favorite: false,
    price: 55.00,
    categoryId: "Womens Watches",
    video: "",
  ),
  Product(
    id: "139",
    title: "ساعة ذكية للنساء",
    description: "ساعة نسائية أنيقة بلون روز جولد.",
    images: [],
    favorite: false,
    price: 55.00,
    categoryId: "Womens Watches",
    video: "",
  ),
  Product(
    id: "140",
    title: "ساعة فاخرة مرصعة",
    description: "ساعة نسائية أنيقة بلون روز جولد.",
    images: [],
    favorite: false,
    price: 55.00,
    categoryId: "Womens Watches",
    video: "",
  ),
  Product(
    id: "141",
    title: "ساعة عملية يومية",
    description: "ساعة نسائية أنيقة بلون روز جولد.",
    images: [],
    favorite: false,
    price: 55.00,
    categoryId: "Womens Watches",
    video: "",
  ),
  Product(
    id: "142",
    title: "ساعة ذهبية وردية",
    description: "ساعة نسائية أنيقة بلون روز جولد.",
    images: [],
    favorite: false,
    price: 55.00,
    categoryId: "Womens Watches",
    video: "",
  ),
  Product(
    id: "143",
    title: "ساعة رياضية نسائية",
    description: "ساعة نسائية أنيقة بلون روز جولد.",
    images: [],
    favorite: false,
    price: 55.00,
    categoryId: "Womens Watches",
    video: "",
  ),
];
